const NAV=[['dashboard','⌂','Overview'],['vehicles','🚗','Vehicles'],['insurance','🛡️','Insurance'],['taxi','🚁','Airlift Taxi'],['rental','🏍️','Dirtbike'],['shop','🛒','Server Shop'],['playershops','🏪','Player Shops'],['squads','👥','Squad Finder'],['lore','📖','Player Lore'],['history','🧾','History']];
const ADMIN=[['admin','⚙️','Admin Tools'],['surveillance','👁️','Surveillance']];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state={me:null,data:null,section:new URLSearchParams(location.search).get('section')||'dashboard'};
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Watcher request failed');return j}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0))}
function fmt(t){return t?new Date(t).toLocaleString():'—'}
function toast(s){const e=$('toast');e.textContent=s;e.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display='none',3500)}
function nav(){const rows=[...NAV,...(state.me?.isAdmin?ADMIN:[])];$('nav').innerHTML=rows.map(([id,ic,l])=>`<button class="${id===state.section?'active':''}" onclick="go('${id}')">${ic}<span>${l}</span></button>`).join('')}
async function load(){state.data=await api('/portal/api/overview');state.me=state.data.me;$('displayName').textContent=state.me.displayName;$('roleText').textContent=state.me.isAdmin?'OWNER / ADMIN CLEARANCE':'THE EXILES CLEARANCE';$('avatar').src=state.me.avatar||'/portal/assets/watcher.jpg';$('sessionState').textContent=`Secure until ${new Date(state.me.sessionExpiresAt).toLocaleTimeString()}`;nav();render();setTimeout(()=>$('boot').classList.add('hide'),500)}
function go(id){state.section=id;history.replaceState({},'',`/portal?section=${id}`);nav();render()}
function title(a,b){$('sectionEyebrow').textContent=a;$('sectionTitle').textContent=b}
function metric(label,val,sub=''){return `<div class="card span3 metric"><small>${label}</small><b>${val}</b><span>${sub}</span></div>`}
function service(id,ic,name,desc,status='Open'){return `<div class="card span4 service" onclick="go('${id}')"><i>${ic}</i><h3>${name}</h3><p>${desc}</p><div style="margin-top:12px"><span class="status good">${status}</span></div></div>`}
function render(){const d=state.data||{};const p=d.player||{};const v=$('view');if(state.section==='dashboard'){title('WATCHER OVERVIEW','Command Dashboard');v.innerHTML=`<div class="grid">${metric('SCUM Character',esc(p.name||'Not linked'),p.online?'ONLINE NOW':'OFFLINE')}${metric('Cash',p.cash==null?'—':money(p.cash),'Live GGCON balance')}${metric('Fame',p.fame??'—','Current fame points')}${metric('Vehicles',d.vehicles?.length||0,'Tracked vehicles')}<div class="card span8"><h3 style="margin-top:0">Welcome back, ${esc(p.name||state.me.displayName)}</h3><p style="color:var(--muted);line-height:1.7">Watcher has assembled your Outpost X services into one secure command network. Everything below is tied to your Discord identity and linked SCUM account.</p><div class="grid" style="margin-top:15px">${service('taxi','🚁','Airlift Taxi','Request emergency transport and view your cooldown.',d.airlift?.ready?'READY':'COOLDOWN')}${service('playershops','🏪','Player Shops','Browse storefronts or manage your own shop.')}${service('lore','📖','Player Lore','Create and browse roleplay character profiles.')}${service('squads','👥','Squad Finder','Find a squad or manage your recruiting post.')}${service('history','🧾','Watcher History','Review 15 days of Watcher activity.')}${service('vehicles','🚗','Vehicles','View your linked vehicles and insurance.')}</div></div><div class="card span4"><h3>Current Status</h3><div class="list">${statusRow('Account Link',p.steamId?'Linked':'Not linked')}${statusRow('Airlift',d.airlift?.ready?'Ready':d.airlift?.nextRide?`Ready ${fmt(d.airlift.nextRide)}`:'Unknown')}${statusRow('Dirtbike',d.rental?.status||'None')}${statusRow('Player Shop',d.myShop?.shop_name||'Not created')}${statusRow('Lore Profile',d.myLore?.character_name||'Not created')}</div></div></div>`}
else if(state.section==='vehicles') renderVehicles(v,d);else if(state.section==='insurance')renderInsurance(v,d);else if(state.section==='taxi')renderTaxi(v,d);else if(state.section==='rental')renderRental(v,d);else if(state.section==='shop')renderServerShop(v,d);else if(state.section==='playershops')renderPlayerShops(v,d);else if(state.section==='squads')renderSquads(v,d);else if(state.section==='lore')renderLore(v,d);else if(state.section==='history')renderHistory(v,d.transactions||[],false);else if(state.section==='admin')renderAdmin(v,d);else if(state.section==='surveillance'){title('ADMIN SURVEILLANCE','48-Hour Movement DVR');v.innerHTML='<iframe class="surveillance" src="/tracker/view"></iframe>'}}
function statusRow(a,b){return `<div class="row"><div><b>${esc(a)}</b></div><span>${esc(b)}</span></div>`}
function renderVehicles(v,d){title('PLAYER ASSETS','Vehicles');const rows=(d.vehicles||[]).map(x=>`<div class="row"><div><b>${esc(x.name||x.vehicleName||'Vehicle')}</b><small>ID ${esc(x.id||x.vehicleId||'Unknown')} • ${esc(x.sector||x.location||'Location unavailable')}</small></div><span class="status">${esc(x.insured?'INSURED':'UNINSURED')}</span></div>`).join('');v.innerHTML=`<div class="card"><div class="list">${rows||'<div class="empty">No vehicles were returned for your linked player.</div>'}</div></div>`}
function renderInsurance(v,d){title('ASSET PROTECTION','Vehicle Insurance');v.innerHTML='<div class="card"><div class="empty">Loading insurance controls…</div></div>';api('/portal/api/insurance/options').then(o=>{const policies=(o.policies||[]).map(x=>`<div class="row"><div><b>${esc(x.vehicle_name||x.vehicle_type||'Vehicle policy')}</b><small>Vehicle ${esc(x.vehicle_id||'—')} • Purchased ${fmt(x.purchased_at)}</small></div><span class="status good">${esc((x.status||'active').toUpperCase())}</span></div>`).join('');const eligible=(o.vehicles||[]).filter(x=>x.eligible).map(x=>`<div class="row"><div><b>${esc(x.label||x.name)}</b><small>Vehicle ID ${esc(x.id)} • ${money(x.price)}</small></div><button class="btn primary" onclick="buyInsurance('${esc(x.id)}')">Insure</button></div>`).join('');const claims=(o.claims||[]).map(x=>`<div class="row"><div><b>${esc(x.policy?.vehicle_name||x.vehicle_name||'Replacement Vehicle')}</b><small>Destroyed vehicle ${esc(x.vehicle_id||'—')}</small></div><button class="btn primary" onclick="redeemInsurance('${esc(x.id)}')">Redeem</button></div>`).join('');v.innerHTML=`<div class="grid"><div class="card span6"><h3>Active Policies</h3><div class="list">${policies||'<div class="empty">No active policies.</div>'}</div></div><div class="card span6"><h3>Available Claims</h3><div class="list">${claims||'<div class="empty">No replacement claims are available.</div>'}</div></div><div class="card span12"><h3>Eligible Vehicles</h3><div class="list">${eligible||'<div class="empty">No eligible uninsured vehicles were found.</div>'}</div></div></div>`}).catch(e=>v.innerHTML=`<div class="card empty">${esc(e.message)}</div>`)}
async function buyInsurance(vehicleId){if(!confirm('Purchase insurance for this vehicle?'))return;try{const r=await api('/portal/api/insurance/buy',{method:'POST',body:JSON.stringify({vehicleId})});toast('Insurance activated.');await refresh();render()}catch(e){toast(e.message)}}
async function redeemInsurance(claimId){if(!confirm('Redeem this insurance claim and spawn the replacement vehicle?'))return;try{await api('/portal/api/insurance/redeem',{method:'POST',body:JSON.stringify({claimId})});toast('Replacement vehicle spawned.');await refresh();render()}catch(e){toast(e.message)}}
function renderTaxi(v,d){title('EMERGENCY TRANSPORT','Airlift Taxi');v.innerHTML=`<div class="grid"><div class="card span8"><h3>Sector Airlift</h3><p style="color:var(--muted)">Airlift cost: <b>${money(1000)}</b>. One use per hour. Watcher validates your account, online status, cash and destination before dispatch.</p><div class="grid">${['D4','D3','D2','D1','D0','C4','C3','C2','C1','C0','B4','B3','B2','B1','B0','A4','A3','A2','A1','A0','Z4','Z3','Z2','Z1','Z0'].map(s=>`<button class="btn" onclick="requestTaxi('${s}')">${s}</button>`).join('')}</div></div><div class="card span4"><h3>Status</h3>${statusRow('Availability',d.airlift?.ready?'READY':'COOLDOWN')}${statusRow('Next Ride',d.airlift?.ready?'Now':fmt(d.airlift?.nextRide))}<p style="font-size:11px;color:var(--muted)">Do not jump during the airlift sequence. Watcher will position you above the selected sector.</p></div></div>`}
async function requestTaxi(sector){if(!confirm(`Request an airlift to sector ${sector} for $1,000?`))return;try{await api('/portal/api/action/taxi',{method:'POST',body:JSON.stringify({sector})});toast(`Airlift dispatched to ${sector}.`);await refresh()}catch(e){toast(e.message)}}
function renderRental(v,d){title('TEMPORARY TRANSPORT','Dirtbike Rental');const r=d.rental||{};v.innerHTML=`<div class="grid"><div class="card span8"><h3>30-Minute Dirtbike Rental</h3><p style="color:var(--muted)">Cost: <b>${money(500)}</b>. Watcher spawns a tracked dirtbike for 30 minutes and removes it automatically when time expires.</p><button class="btn primary" onclick="requestRental()" ${r.status==='active'?'disabled':''}>${r.status==='active'?'Rental Active':'Rent Dirtbike'}</button></div><div class="card span4"><h3>Rental Status</h3>${statusRow('Status',r.status||'None')}${statusRow('Vehicle ID',r.vehicle_id||'—')}${statusRow('Expires',fmt(r.expires_at))}</div></div>`}
async function requestRental(){if(!confirm('Rent a dirtbike for $500?'))return;try{await api('/portal/api/action/rental',{method:'POST',body:'{}'});toast('Dirtbike rental started.');await refresh()}catch(e){toast(e.message)}}
function renderServerShop(v,d){title('WATCHER SUPPLY NETWORK','Server Shop');v.innerHTML=`<div class="grid">${(d.shopCatalog||[]).map(x=>`<div class="card span4 shopproduct"><div style="font-size:34px">${esc(x.emoji||'📦')}</div><h3>${esc(x.name)}</h3><p style="color:var(--muted);min-height:42px">${esc(x.description||'Emergency supply package')}</p><div class="list" style="margin:12px 0">${(x.contents||[]).map(i=>`<div class="row"><span>${esc(i.label)}</span><b>×${Number(i.qty||1)}</b></div>`).join('')}</div><b style="font-size:24px">${money(x.price)}</b><div style="margin-top:14px"><button class="btn primary" onclick="buyItem('${esc(x.id)}','${esc(x.name)}',${Number(x.price||0)})">Purchase & Deliver</button></div></div>`).join('')||'<div class="card span12 empty">No server-shop packages are configured.</div>'}</div>`}
async function buyItem(id,name,price){if(!confirm(`Purchase ${name} for ${money(price)} and deliver it beside your linked SCUM character?`))return;try{const r=await api('/portal/api/action/shop',{method:'POST',body:JSON.stringify({id})});toast(`${r.package?.name||name} delivered near ${r.playerName||'your character'}.`);await refresh()}catch(e){toast(e.message)}}
function renderCollection(v,eye,t,items,card){title(eye,t);v.innerHTML=`<div class="searchbar"><input id="filter" placeholder="Search ${t.toLowerCase()}" oninput="filterCards()"></div><div class="grid" id="cards">${items.map(card).join('')||'<div class="card span12 empty">Nothing has been published yet.</div>'}</div>`}
function filterCards(){const q=$('filter').value.toLowerCase();document.querySelectorAll('#cards>[data-search]').forEach(e=>e.style.display=e.dataset.search.includes(q)?'block':'none')}
function imageStrip(urls){const a=Array.isArray(urls)?urls.filter(Boolean):[];return a.length?`<div class="imageStrip">${a.map(u=>`<img src="${esc(u)}" loading="lazy">`).join('')}</div>`:''}
function shopCard(x){return `<div class="card span4" data-search="${esc(`${x.shop_name} ${x.owner_name||''} ${x.shop_type} ${x.location_text||''}`.toLowerCase())}">${imageStrip(x.image_urls)}<span class="status ${x.is_open?'good':''}">${x.is_open?'OPEN':'CLOSED'}</span><h3>${esc(x.shop_name||'Player Shop')}</h3><p>${esc(x.description||'No description')}</p><small>${esc(x.location_text||'Location hidden')} • ${esc(x.shop_type||'General')}</small>${x.storefront_text?`<p class="ownerText">${esc(x.storefront_text)}</p>`:''}</div>`}
function squadCard(x){return `<div class="card span4" data-search="${esc(`${x.squad_name} ${x.play_style} ${x.active_times}`.toLowerCase())}"><span class="status ${x.is_recruiting?'good':''}">${x.is_recruiting?'RECRUITING':'CLOSED'}</span><h3>${esc(x.squad_name||'Squad')}</h3><p>${esc(x.description||'No description')}</p><div class="list compact">${statusRow('Members',x.member_count||'Not listed')}${statusRow('Style',x.play_style||'Any')}${statusRow('Active',x.active_times||'Any time')}${statusRow('Voice',x.voice_chat||'Optional')}</div></div>`}
function loreCard(x){return `<div class="card span4" data-search="${esc(`${x.character_name} ${x.category} ${x.faction_squad||''} ${x.origin}`.toLowerCase())}">${imageStrip(x.image_urls)}<span class="status good">${esc(x.rp_status||'RP')}</span><h3>${esc(x.character_name||'Unknown Survivor')}</h3><p>${esc(x.backstory||x.personality||'No lore summary')}</p><small>${esc(x.category||'Survivor')} • ${esc(x.faction_squad||'Unaffiliated')}</small></div>`}
function manageBar(titleText,desc,buttons){return `<div class="card span12 manageHero"><div><small>YOUR LISTING</small><h2>${esc(titleText)}</h2><p>${esc(desc)}</p></div><div class="adminActions">${buttons}</div></div>`}
function renderPlayerShops(v,d){title('PLAYER MARKETPLACE','Player Shops');const mine=d.myShop;const controls=mine?manageBar(mine.shop_name,mine.is_open?'Your storefront is open.':'Your storefront is closed.',`<button class="btn primary" onclick="openShopForm()">Edit Shop</button><button class="btn" onclick="openShopImages()">Manage Images</button><button class="btn" onclick="shopAction('toggle')">${mine.is_open?'Close':'Open'} Shop</button><button class="btn dangerBtn" onclick="shopAction('delete')">Delete Shop</button>`):manageBar('Create Your Storefront','A Shop Owner role is required. Trading still happens in SCUM.',`<button class="btn primary" onclick="openShopForm()">Create Shop</button>`);v.innerHTML=`<div class="grid">${controls}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search shops" oninput="filterCards()"></div><div class="grid" id="cards">${(d.shops||[]).map(shopCard).join('')||'<div class="empty">No shops yet.</div>'}</div></div></div>`}
function openShopForm(){const x=state.data.myShop||{};$('modalBody').innerHTML=`<h2>${x.id?'Edit':'Create'} Player Shop</h2><div class="formgrid"><label>Shop Name<input id="fShopName" maxlength="80" value="${esc(x.shop_name||'')}"></label><label>Location / Sector<input id="fShopLocation" maxlength="100" value="${esc(x.location_text||'')}"></label><label>Shop Type<input id="fShopType" maxlength="80" value="${esc(x.shop_type||'General')}"></label><label class="full">Description<textarea id="fShopDesc" rows="5">${esc(x.description||'')}</textarea></label><label class="full">Text Below Images<textarea id="fShopText" rows="4">${esc(x.storefront_text||'')}</textarea></label></div><button class="btn primary" onclick="saveShop()">Save Storefront</button>`;$('modal').classList.remove('hidden')}
async function saveShop(){const body={shop_name:$('fShopName').value,location_text:$('fShopLocation').value,shop_type:$('fShopType').value,description:$('fShopDesc').value,storefront_text:$('fShopText').value};try{await api(`/portal/api/player-shop/${state.data.myShop?'update':'create'}`,{method:'POST',body:JSON.stringify(body)});closeModal();toast('Shop saved.');await refresh()}catch(e){toast(e.message)}}
function openShopImages(){const x=state.data.myShop||{};$('modalBody').innerHTML=`<h2>Shop Images</h2><p>Choose up to 5 images. Saving replaces the current image set; leave empty to remove all images.</p><label>Images<input id="shopFiles" type="file" accept="image/*" multiple></label><label>Text Below Images<textarea id="shopCaption" rows="4">${esc(x.storefront_text||'')}</textarea></label><button class="btn primary" onclick="saveShopImages()">Replace Images</button>`;$('modal').classList.remove('hidden')}
async function filesToData(input){const files=[...input.files].slice(0,5);return Promise.all(files.map(f=>new Promise((resolve,reject)=>{if(f.size>8*1024*1024)return reject(new Error(`${f.name} is larger than 8 MB.`));const r=new FileReader();r.onload=()=>resolve({name:f.name,data:r.result});r.onerror=()=>reject(new Error(`Could not read ${f.name}.`));r.readAsDataURL(f)})))}
async function saveShopImages(){try{const images=await filesToData($('shopFiles'));await api('/portal/api/player-shop/images',{method:'POST',body:JSON.stringify({images,storefront_text:$('shopCaption').value})});closeModal();toast('Shop images updated.');await refresh()}catch(e){toast(e.message)}}
async function shopAction(action){if(action==='delete'&&!confirm('Permanently delete your shop?'))return;try{await api(`/portal/api/player-shop/${action}`,{method:'POST',body:'{}'});toast(action==='delete'?'Shop deleted.':'Shop status updated.');await refresh()}catch(e){toast(e.message)}}
function renderSquads(v,d){title('SQUAD NETWORK','Squad Finder');const mine=d.mySquad;const controls=mine?manageBar(mine.squad_name,mine.is_recruiting?'Your squad is recruiting.':'Your listing is closed.',`<button class="btn primary" onclick="openSquadForm()">Edit Listing</button><button class="btn" onclick="squadAction('toggle')">${mine.is_recruiting?'Stop':'Start'} Recruiting</button><button class="btn dangerBtn" onclick="squadAction('delete')">Delete Listing</button>`):manageBar('Post Your Squad','Create one listing and manage it yourself.',`<button class="btn primary" onclick="openSquadForm()">Create Listing</button>`);v.innerHTML=`<div class="grid">${controls}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search squads" oninput="filterCards()"></div><div class="grid" id="cards">${(d.squads||[]).map(squadCard).join('')||'<div class="empty">No squads listed.</div>'}</div></div></div>`}
function openSquadForm(){const x=state.data.mySquad||{};$('modalBody').innerHTML=`<h2>${x.id?'Edit':'Create'} Squad Listing</h2><div class="formgrid"><label>Squad Name<input id="sqName" value="${esc(x.squad_name||'')}"></label><label>Member Count<input id="sqMembers" value="${esc(x.member_count||'')}"></label><label>Play Style<input id="sqStyle" value="${esc(x.play_style||'')}"></label><label>Active Times<input id="sqTimes" value="${esc(x.active_times||'')}"></label><label>Voice Chat<select id="sqVoice"><option>Optional</option><option>Required</option><option>Not Used</option></select></label><label class="full">Description<textarea id="sqDesc" rows="5">${esc(x.description||'')}</textarea></label></div><button class="btn primary" onclick="saveSquad()">Save Listing</button>`;$('sqVoice').value=x.voice_chat||'Optional';$('modal').classList.remove('hidden')}
async function saveSquad(){const b={squad_name:$('sqName').value,member_count:$('sqMembers').value,play_style:$('sqStyle').value,active_times:$('sqTimes').value,voice_chat:$('sqVoice').value,description:$('sqDesc').value};try{await api(`/portal/api/squad/${state.data.mySquad?'update':'create'}`,{method:'POST',body:JSON.stringify(b)});closeModal();toast('Squad listing saved.');await refresh()}catch(e){toast(e.message)}}
async function squadAction(action){if(action==='delete'&&!confirm('Delete your Squad Finder listing?'))return;try{await api(`/portal/api/squad/${action}`,{method:'POST',body:'{}'});toast('Squad listing updated.');await refresh()}catch(e){toast(e.message)}}
const LORE_CATS=['Survivor','Trader','Mercenary','Medic','Mechanic','Hunter','Military','Drifter','Outlaw / Bandit','Faction Member','Civilian','Other'];
function renderLore(v,d){title('ROLEPLAY ARCHIVE','Player Lore');const mine=d.myLore;const controls=mine?manageBar(mine.character_name,mine.is_published?'Your lore is published.':'Your lore is hidden.',`<button class="btn primary" onclick="openLoreForm()">Edit Lore</button><button class="btn" onclick="openLoreImages()">Manage Images</button><button class="btn" onclick="loreAction('toggle')">${mine.is_published?'Hide':'Publish'} Lore</button><button class="btn dangerBtn" onclick="loreAction('delete')">Delete Lore</button>`):manageBar('Create Your Character','Build a full RP profile with categories, status and images.',`<button class="btn primary" onclick="openLoreForm()">Create Lore</button>`);v.innerHTML=`<div class="grid">${controls}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search names, categories, factions or origin" oninput="filterCards()"></div><div class="grid" id="cards">${(d.lore||[]).map(loreCard).join('')||'<div class="empty">No published lore yet.</div>'}</div></div></div>`}
function openLoreForm(){const x=state.data.myLore||{};$('modalBody').innerHTML=`<h2>${x.id?'Edit':'Create'} Player Lore</h2><div class="formgrid"><label>Character Name<input id="loName" value="${esc(x.character_name||'')}"></label><label>Title / Nickname<input id="loTitle" value="${esc(x.title_nickname||'')}"></label><label>Faction / Squad<input id="loFaction" value="${esc(x.faction_squad||'')}"></label><label>Origin<input id="loOrigin" value="${esc(x.origin||'')}"></label><label>Category<select id="loCat">${LORE_CATS.map(c=>`<option>${c}</option>`).join('')}</select></label><label>RP Status<select id="loStatus"><option>Open to RP</option><option>Casual RP</option><option>Not Seeking RP</option></select></label><label class="full">Backstory<textarea id="loBack" rows="8">${esc(x.backstory||'')}</textarea></label><label class="full">Personality<textarea id="loPerson" rows="4">${esc(x.personality||'')}</textarea></label><label class="full">Goals / Motives<textarea id="loGoals" rows="4">${esc(x.goals||'')}</textarea></label><label class="full">Additional Lore<textarea id="loExtra" rows="4">${esc(x.extra_lore||'')}</textarea></label></div><button class="btn primary" onclick="saveLore()">Save Lore</button>`;$('loCat').value=x.category||'Survivor';$('loStatus').value=x.rp_status||'Casual RP';$('modal').classList.remove('hidden')}
async function saveLore(){const b={character_name:$('loName').value,title_nickname:$('loTitle').value,faction_squad:$('loFaction').value,origin:$('loOrigin').value,category:$('loCat').value,rp_status:$('loStatus').value,backstory:$('loBack').value,personality:$('loPerson').value,goals:$('loGoals').value,extra_lore:$('loExtra').value};try{await api(`/portal/api/lore/${state.data.myLore?'update':'create'}`,{method:'POST',body:JSON.stringify(b)});closeModal();toast('Lore saved.');await refresh()}catch(e){toast(e.message)}}
function openLoreImages(){const x=state.data.myLore||{};$('modalBody').innerHTML=`<h2>Lore Images</h2><p>Choose up to 5 images. Saving replaces the current image set; leave empty to remove all images.</p><label>Images<input id="loreFiles" type="file" accept="image/*" multiple></label><label>Image Caption<textarea id="loreCaption" rows="4">${esc(x.image_caption||'')}</textarea></label><button class="btn primary" onclick="saveLoreImages()">Replace Images</button>`;$('modal').classList.remove('hidden')}
async function saveLoreImages(){try{const images=await filesToData($('loreFiles'));await api('/portal/api/lore/images',{method:'POST',body:JSON.stringify({images,image_caption:$('loreCaption').value})});closeModal();toast('Lore images updated.');await refresh()}catch(e){toast(e.message)}}
async function loreAction(action){if(action==='delete'&&!confirm('Permanently delete your lore profile?'))return;try{await api(`/portal/api/lore/${action}`,{method:'POST',body:'{}'});toast('Lore profile updated.');await refresh()}catch(e){toast(e.message)}}
function renderHistory(v,tx,admin){if(v.id!=='adminLedger')title(admin?'ADMIN LEDGER':'WATCHER LEDGER',admin?'Transaction Control':'My Watcher History');v.innerHTML=`<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>Date</th>${admin?'<th>Player</th>':''}<th>Action</th><th>Amount</th><th>Status</th>${admin?'<th>Admin</th>':''}</tr></thead><tbody>${tx.map(x=>`<tr><td>${fmt(x.created_at)}</td>${admin?`<td>${esc(x.player_name||x.steam_id||'Unknown')}</td>`:''}<td>${esc(x.title||x.type)}</td><td class="amount ${Number(x.amount)>=0?'pos':'neg'}">${Number(x.amount)?money(x.amount):'—'}</td><td>${esc(x.refund_status||x.status)}</td>${admin?`<td>${x.refundable&&Math.abs(Number(x.amount||0))>Number(x.refunded_amount||0)?`<button class="btn" onclick='refund(${JSON.stringify(x)})'>Refund</button>`:'—'}</td>`:''}</tr>`).join('')||'<tr><td colspan="6" class="empty">No Watcher history in the last 15 days.</td></tr>'}</tbody></table></div></div>`}
function renderAdmin(v,d){if(!state.me.isAdmin)return go('dashboard');title('ADMIN OPERATIONS','Watcher Control Deck');v.innerHTML=`<div class="adminTabs"><button class="btn primary" onclick="adminTab('players')">Player Controls</button><button class="btn" onclick="adminTab('ledger')">Transaction Ledger & Refunds</button><button class="btn" onclick="adminTab('content')">Player Content Moderation</button></div><div id="adminArea"></div>`;adminTab('players')}
function adminTab(tab){const a=$('adminArea');if(tab==='ledger'){renderAdminLedger(a);return}if(tab==='content'){renderContentModeration(a);return}a.innerHTML=`<div class="grid"><div class="card span12"><h3>Find a Player</h3><p style="color:var(--muted)">Search by SCUM name or Steam64 ID. Raw log/data-pull commands stay in Discord and are intentionally not shown here.</p><div class="searchbar"><input id="adminSearch" placeholder="Player name or Steam64 ID" onkeydown="if(event.key==='Enter')adminSearch()"><button class="btn primary" onclick="adminSearch()">Search</button></div><div id="adminResults" class="list"></div></div><div id="adminPlayer" class="span12"></div></div>`}
function renderContentModeration(a){const d=state.data;a.innerHTML=`<div class="grid"><div class="card span4"><h3>Player Shops</h3><div class="list">${(d.shops||[]).map(x=>moderationRow('shop',x.id,x.shop_name,x.is_open?'OPEN':'CLOSED')).join('')||'<div class="empty">None</div>'}</div></div><div class="card span4"><h3>Squad Listings</h3><div class="list">${(d.squads||[]).map(x=>moderationRow('squad',x.id,x.squad_name,x.is_recruiting?'RECRUITING':'CLOSED')).join('')||'<div class="empty">None</div>'}</div></div><div class="card span4"><h3>Player Lore</h3><div class="list">${[...(d.lore||[]),...(d.myLore&&!d.lore?.some(x=>x.id===d.myLore.id)?[d.myLore]:[])].map(x=>moderationRow('lore',x.id,x.character_name,x.is_published?'PUBLISHED':'HIDDEN')).join('')||'<div class="empty">None</div>'}</div></div></div>`}
function moderationRow(kind,id,name,status){return `<div class="row"><div><b>${esc(name)}</b><small>${esc(status)}</small></div><div><button class="btn" onclick="moderateContent('${kind}','${esc(id)}','toggle')">Toggle</button> <button class="btn dangerBtn" onclick="moderateContent('${kind}','${esc(id)}','delete')">Delete</button></div></div>`}
async function moderateContent(kind,id,action){if(action==='delete'&&!confirm(`Delete this ${kind} permanently?`))return;try{await api('/portal/api/admin/content',{method:'POST',body:JSON.stringify({kind,id,action})});toast('Content updated.');await refresh();go('admin');adminTab('content')}catch(e){toast(e.message)}}
function renderAdminLedger(a){a.innerHTML='<div id="adminLedger"></div>';const box=$('adminLedger');const original=$('view');const old=original.innerHTML;renderHistory(box,state.data?.adminTransactions||[],true)}
async function adminSearch(){const q=$('adminSearch').value.trim();if(!q)return toast('Enter a player name or Steam ID.');try{const r=await api('/portal/api/admin/search',{method:'POST',body:JSON.stringify({query:q})});$('adminResults').innerHTML=(r.players||[]).map(p=>`<button class="row adminresult" onclick="openAdminPlayer('${esc(p.steamId)}','${esc(p.name)}')"><div><b>${esc(p.name)}</b><small>${esc(p.steamId)}</small></div><span class="status ${p.online?'good':''}">${p.online?'ONLINE':'OFFLINE'}</span></button>`).join('')||'<div class="empty">No players matched that search.</div>'}catch(e){toast(e.message)}}
function openAdminPlayer(steamId,name){$('adminPlayer').innerHTML=`<div class="card"><div class="playerHead"><div><small>SELECTED PLAYER</small><h2>${esc(name)}</h2><span>${esc(steamId)}</span></div><button class="btn" onclick="adminView('${steamId}','details')">Refresh Details</button></div><div class="adminActions"><button class="btn primary" onclick="adminView('${steamId}','details')">Player Details</button><button class="btn" onclick="adminView('${steamId}','vehicles')">Vehicles</button><button class="btn" onclick="adminView('${steamId}','squad')">Squad</button><button class="btn" onclick="adminView('${steamId}','nearby')">Nearby Vehicles</button><button class="btn" onclick="adminAdjustOpen('${steamId}','cash',1)">Add Cash</button><button class="btn dangerBtn" onclick="adminAdjustOpen('${steamId}','cash',-1)">Remove Cash</button><button class="btn" onclick="adminAdjustOpen('${steamId}','fame',1)">Add Fame</button><button class="btn dangerBtn" onclick="adminAdjustOpen('${steamId}','fame',-1)">Remove Fame</button><button class="btn dangerBtn" onclick="adminJail('${steamId}','jail')">Jail</button><button class="btn" onclick="adminJail('${steamId}','unjail')">Unjail</button><button class="btn dangerBtn" onclick="adminModerateOpen('${steamId}','ban')">Ban Player</button><button class="btn" onclick="adminModerateOpen('${steamId}','unban')">Unban Player</button><button class="btn dangerBtn" onclick="adminModerateOpen('${steamId}','unlink')">Unlink Discord</button></div><pre class="adminOutput" id="adminOutput">Select an action above.</pre></div>`;adminView(steamId,'details')}
async function adminView(steamId,view){const o=$('adminOutput');o.textContent='Watcher is loading…';try{const r=await api('/portal/api/admin/player',{method:'POST',body:JSON.stringify({steamId,view})});o.textContent=r.content||'No data returned.'}catch(e){o.textContent=e.message}}
function adminAdjustOpen(steamId,kind,sign){$('modalBody').innerHTML=`<h2>${sign>0?'Add':'Remove'} ${kind==='cash'?'Cash':'Fame'}</h2><div class="formgrid"><label>Amount<input id="adminAmount" type="number" min="1"></label><label class="full">Required reason<textarea id="adminReason" rows="4"></textarea></label></div><button class="btn primary" onclick="adminAdjust('${steamId}','${kind}',${sign})">Confirm Adjustment</button>`;$('modal').classList.remove('hidden')}
async function adminAdjust(steamId,kind,sign){const n=Math.floor(Number($('adminAmount').value)),reason=$('adminReason').value.trim();if(!n||n<1||!reason)return toast('Enter an amount and reason.');try{await api('/portal/api/admin/adjust',{method:'POST',body:JSON.stringify({steamId,kind,amount:n*sign,reason})});closeModal();toast('Player balance updated.');adminView(steamId,'details')}catch(e){toast(e.message)}}
async function adminJail(steamId,action){if(!confirm(`${action==='jail'?'Jail':'Release'} this player?`))return;try{const r=await api('/portal/api/admin/jail',{method:'POST',body:JSON.stringify({steamId,action})});toast(r.message||'Action completed.');adminView(steamId,'details')}catch(e){toast(e.message)}}
function adminModerateOpen(steamId,action){const word=action.toUpperCase(),needsReason=action!=='unlink';$('modalBody').innerHTML=`<h2>${word} Player</h2>${needsReason?'<label>Required reason<textarea id="modReason" rows="4"></textarea></label>':''}<label>Type ${word} to confirm<input id="modConfirm"></label><button class="btn ${action==='ban'||action==='unlink'?'dangerBtn':'primary'}" onclick="adminModerate('${steamId}','${action}')">Confirm ${word}</button>`;$('modal').classList.remove('hidden')}
async function adminModerate(steamId,action){const reason=$('modReason')?.value.trim()||'',confirmWord=$('modConfirm').value.trim();try{const r=await api('/portal/api/admin/moderate',{method:'POST',body:JSON.stringify({steamId,action,reason,confirm:confirmWord})});closeModal();toast(r.message||'Action completed.')}catch(e){toast(e.message)}}
function refund(x){$('modalBody').innerHTML=`<h2>Refund Transaction</h2><p>${esc(x.player_name||x.steam_id)} • ${esc(x.title)}</p><div class="formgrid"><label>Refund amount<input id="refundAmount" type="number" min="1" max="${Math.abs(Number(x.amount))-Number(x.refunded_amount||0)}" value="${Math.abs(Number(x.amount))-Number(x.refunded_amount||0)}"></label><label class="full">Required reason<textarea id="refundReason" rows="4"></textarea></label></div><button class="btn primary" style="margin-top:12px" onclick="confirmRefund('${x.id}')">Issue Refund</button>`;$('modal').classList.remove('hidden')}
async function confirmRefund(id){const amount=Number($('refundAmount').value),reason=$('refundReason').value.trim();if(!reason)return toast('A refund reason is required.');try{await api('/portal/api/admin/refund',{method:'POST',body:JSON.stringify({transactionId:id,amount,reason})});closeModal();toast('Refund completed.');await refresh();go('admin')}catch(e){toast(e.message)}}
function closeModal(){$('modal').classList.add('hidden')}
async function refresh(){state.data=await api('/portal/api/overview');state.me=state.data.me;render()}
$('refreshBtn').onclick=refresh;load().catch(e=>{document.body.innerHTML=`<div style="padding:40px;color:#ff8d8d"><h2>Command Center unavailable</h2><p>${esc(e.message)}</p></div>`});
