const NAV=[['dashboard','⌂','Overview'],['staff','🛡️','Staff'],['vehicles','🚗','Vehicles'],['insurance','🛡️','Insurance'],['taxi','🚁','Airlift Taxi'],['rental','🏍️','Dirtbike'],['shop','🛒','Server Shop'],['events','📅','Events'],['playershops','🏪','Player Shops'],['squads','👥','Squad Finder'],['lore','📖','Player Lore'],['history','🧾','History']];
const REGISTER_CHANNEL_ID='1517255357888466964';
const PUBLIC_UNREGISTERED_SECTIONS=new Set(['dashboard','staff']);
function registrationLocked(){return !!state.me&&!state.me.isAdmin&&!state.me.isOwner&&!state.me.registered}
function registrationGateMarkup(){return `<div class="grid"><div class="card span12"><small>SCUM LINK REQUIRED</small><h2>Register Before Using Player Services</h2><p style="color:var(--muted);line-height:1.7">Your Discord account is allowed into the Command Center, but it is not linked to a SCUM character yet. Events, shops, squads, lore, vehicles, rentals, insurance, Airlift Taxi, and Watcher history stay locked until registration is complete.</p><div class="adminActions"><a class="btn primary" href="https://discord.com/channels/1516269432538661025/${REGISTER_CHANNEL_ID}" target="_blank" rel="noopener">Open Player Registration</a><button class="btn" onclick="refresh().then(()=>go('dashboard'))">Check Registration</button></div><small>Click Register Steam in Discord, type the code in SCUM chat, and Watcher will link you automatically.</small></div></div>`}
const ADMIN=[['admin','⚙️','Admin Tools'],['surveillance','👁️','Surveillance']];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state={me:null,data:null,section:new URLSearchParams(location.search).get('section')||sessionStorage.getItem('watcherPortalSection')||'dashboard',navHistory:[],sessionExpiresAt:0,sessionTimer:null,sessionWarningShown:false,sessionExpired:false,overviewHash:'',portalRevision:0,autoRefreshTimer:null,lastAutoRefreshAt:0,adminSubtab:'players',adminLedger:{page:1,pageSize:25,category:'all',status:'all',search:'',total:0,pages:1,rows:[]}};
const DRAFT_PREFIX='watcherPortalDraft:';
function mutationMethod(opt={}){return String(opt.method||'GET').toUpperCase()}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const renewed=r.headers.get('X-Watcher-Session-Expires');if(renewed)startSessionClock(renewed);const j=await r.json().catch(()=>({}));if(r.status===401){expireSession();throw new Error('Your secure session has expired. Please reopen the Command Center from Discord.')}if(!r.ok)throw new Error(j.error||'Watcher request failed');if(['POST','PUT','PATCH','DELETE'].includes(mutationMethod(opt))){try{localStorage.setItem('watcherPortalUpdate',JSON.stringify({at:Date.now(),path}))}catch{}}return j}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0))}
function fmt(t){return t?new Date(t).toLocaleString():'—'}
function toast(s){const e=$('toast');e.textContent=s;e.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display='none',3500)}
function draftKey(name){const who=state.me?.discordId||state.me?.id||state.me?.displayName||'user';return `${DRAFT_PREFIX}${who}:${name}`}
function saveDraft(name,extra={}){const modal=$('modal');if(!modal||modal.classList.contains('hidden'))return;const values={};modal.querySelectorAll('input:not([type=file]),textarea,select').forEach(el=>{if(!el.id)return;values[el.id]=el.type==='checkbox'?el.checked:el.value});try{localStorage.setItem(draftKey(name),JSON.stringify({savedAt:Date.now(),section:state.section,values,...extra}))}catch{}}
function readDraft(name,maxAge=604800000){try{const raw=localStorage.getItem(draftKey(name));if(!raw)return null;const d=JSON.parse(raw);if(!d?.savedAt||Date.now()-d.savedAt>maxAge){localStorage.removeItem(draftKey(name));return null}return d}catch{return null}}
function clearDraft(name){try{localStorage.removeItem(draftKey(name))}catch{}}
function restoreDraft(name,{extraRestore}={}){const d=readDraft(name);if(!d)return false;for(const [id,val] of Object.entries(d.values||{})){const el=$(id);if(!el)continue;if(el.type==='checkbox')el.checked=!!val;else el.value=val}if(extraRestore)extraRestore(d);toast(`Recovered your unsaved work from ${new Date(d.savedAt).toLocaleTimeString()}.`);return true}
function armDraft(name,extraProvider){const modal=$('modal');if(!modal)return;const save=()=>saveDraft(name,typeof extraProvider==='function'?extraProvider():{});modal.querySelectorAll('input,textarea,select').forEach(el=>{if(el.type==='file')return;el.addEventListener('input',save);el.addEventListener('change',save)});saveDraft.active={name,save}}
function modalBusy(){const modal=$('modal');if(modal&&!modal.classList.contains('hidden'))return true;const a=document.activeElement;return !!a&&['INPUT','TEXTAREA','SELECT'].includes(a.tagName)}
function stableHash(data){try{return JSON.stringify(data)}catch{return String(Date.now())}}
function preserveUi(){return {scrollY:window.scrollY,filter:$('filter')?.value||'',shopManagerFilter:$('shopManagerFilter')?.value||'',adminSubtab:state.adminSubtab}}
function restoreUi(ui){if(ui.filter&&$('filter')){$('filter').value=ui.filter;filterCards()}if(ui.shopManagerFilter&&$('shopManagerFilter')){$('shopManagerFilter').value=ui.shopManagerFilter;filterShopManagerCards()}requestAnimationFrame(()=>window.scrollTo(0,ui.scrollY||0))}
async function silentRefresh(force=false){if(state.sessionExpired||document.hidden||(!force&&modalBusy()))return;try{if(!force){const rev=await api('/portal/api/revision');if(Number(rev.revision||0)===Number(state.portalRevision||0))return;state.portalRevision=Number(rev.revision||0)}const fresh=await api('/portal/api/overview');const ui=preserveUi();state.data=fresh;state.me=fresh.me;state.overviewHash=stableHash(fresh);nav();render();if(state.section==='admin'&&ui.adminSubtab&&ui.adminSubtab!=='players')setTimeout(()=>adminTab(ui.adminSubtab),0);restoreUi(ui);state.lastAutoRefreshAt=Date.now()}catch(e){if(!state.sessionExpired)console.warn('Portal auto-refresh skipped:',e.message)}}
function startAutoRefresh(){clearInterval(state.autoRefreshTimer);state.autoRefreshTimer=setInterval(()=>silentRefresh(false),45000)}
window.addEventListener('storage',e=>{if(e.key==='watcherPortalUpdate')silentRefresh(true)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)silentRefresh(false)});
window.addEventListener('beforeunload',()=>{try{sessionStorage.setItem('watcherPortalSection',state.section);sessionStorage.setItem('watcherPortalScroll',String(window.scrollY))}catch{}if(saveDraft.active?.save)saveDraft.active.save()});
function formatRemaining(ms){const total=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(total/60),sec=total%60;return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function startSessionClock(expiresAt){state.sessionExpiresAt=Date.parse(expiresAt||'');if(!Number.isFinite(state.sessionExpiresAt))return;clearInterval(state.sessionTimer);updateSessionClock();state.sessionTimer=setInterval(updateSessionClock,1000)}
function updateSessionClock(){if(state.sessionExpired)return;const left=state.sessionExpiresAt-Date.now();const label=$('sessionState');if(label)label.textContent=left>0?`Session ${formatRemaining(left)}`:'Session expired';const countdown=$('sessionWarningCountdown');if(countdown)countdown.textContent=`${formatRemaining(left)} remaining`;if(left<=0){expireSession();return}if(left<=5*60*1000&&!state.sessionWarningShown){state.sessionWarningShown=true;$('sessionWarning')?.classList.remove('hidden')}}
function dismissSessionWarning(){$('sessionWarning')?.classList.add('hidden')}
function expireSession(){if(state.sessionExpired)return;if(saveDraft.active?.save)saveDraft.active.save();try{sessionStorage.setItem('watcherPortalSection',state.section);sessionStorage.setItem('watcherPortalScroll',String(window.scrollY))}catch{}state.sessionExpired=true;clearInterval(state.sessionTimer);document.body.innerHTML=`<main class="expiredScreen"><div class="sessionPanel expiredPanel"><img src="/portal/assets/watcher.jpg" alt="The Watcher"><span class="sessionKicker">SECURE CONNECTION CLOSED</span><h1>Command Center Session Expired</h1><p>Your secure access window has ended and all Command Center actions are now disabled.</p><strong>Please reopen the Command Center from Discord.</strong><div class="sessionActions"><a class="btn primary" href="https://discord.com/channels/1516269432538661025/1531709557997306027" target="_blank" rel="noopener">Open Discord Command Center</a><button class="btn" id="closeExpiredWindow">Close Window</button></div><small>Your unsaved draft was preserved. Use the permanent Discord button to reopen the Command Center and continue.</small></div></main>`;document.getElementById('closeExpiredWindow')?.addEventListener('click',()=>window.close())}

function nav(){const adminRows=state.me?.isAdmin?ADMIN.filter(([id])=>id!=='surveillance'||state.me?.isOwner||state.me?.permissions?.use_surveillance):[];const playerRows=registrationLocked()?NAV.filter(([id])=>PUBLIC_UNREGISTERED_SECTIONS.has(id)):NAV;const rows=[...playerRows,...adminRows];$('nav').innerHTML=rows.map(([id,ic,l])=>`<button class="${id===state.section?'active':''}" onclick="go('${id}')">${ic}<span>${l}</span></button>`).join('')}
async function load(){state.data=await api('/portal/api/overview');state.me=state.data.me;state.overviewHash=stableHash(state.data);try{const rev=await api('/portal/api/revision');state.portalRevision=Number(rev.revision||0)}catch{}$('displayName').textContent=state.me.displayName;$('roleText').textContent=state.me.isOwner?'OWNER EYES ONLY':state.me.isAdmin?'ADMIN CLEARANCE':'THE EXILES CLEARANCE';$('avatar').src=state.me.avatar||'/portal/assets/watcher.jpg';startSessionClock(state.me.sessionExpiresAt);nav();render();startAutoRefresh();setTimeout(()=>{const y=Number(sessionStorage.getItem('watcherPortalScroll')||0);window.scrollTo(0,y);$('boot').classList.add('hide')},500)}
function updatePageNav(){const back=$('backBtn'),home=$('homeBtn');if(back)back.disabled=!state.navHistory.length;if(home)home.disabled=state.section==='dashboard'}
function go(id,opt={}){if(registrationLocked()&&!PUBLIC_UNREGISTERED_SECTIONS.has(id)){toast('Register your SCUM character before using that service.');id='dashboard'}if(!id||id===state.section){updatePageNav();return}if(!opt.fromBack){state.navHistory.push(state.section);if(state.navHistory.length>30)state.navHistory.shift()}state.section=id;try{sessionStorage.setItem('watcherPortalSection',id)}catch{}history.replaceState({section:id},'',`/portal?section=${id}`);nav();render();updatePageNav();window.scrollTo({top:0,behavior:opt.instant?'auto':'smooth'})}
function goBack(){const id=state.navHistory.pop()||'dashboard';go(id,{fromBack:true})}
function goHome(){go('dashboard')}
function title(a,b){$('sectionEyebrow').textContent=a;$('sectionTitle').textContent=b}
function metric(label,val,sub=''){return `<div class="card span3 metric"><small>${label}</small><b>${val}</b><span>${sub}</span></div>`}
function service(id,ic,name,desc,status='Open'){return `<div class="card span4 service" onclick="go('${id}')"><i>${ic}</i><h3>${name}</h3><p>${desc}</p><div style="margin-top:12px"><span class="status good">${status}</span></div></div>`}
function render(){const d=state.data||{};const p=d.player||{};const v=$('view');if(registrationLocked()&&!PUBLIC_UNREGISTERED_SECTIONS.has(state.section))state.section='dashboard';if(registrationLocked()&&state.section==='dashboard'){title('REGISTRATION REQUIRED','Command Center Locked');v.innerHTML=registrationGateMarkup();updatePageNav();return}if(state.section==='dashboard'){title('WATCHER OVERVIEW','Command Dashboard');v.innerHTML=`<div class="grid">${metric('SCUM Character',esc(p.name||'Not linked'),p.online?'ONLINE NOW':'OFFLINE')}${metric('Cash',p.cash==null?'—':money(p.cash),'Live GGCON balance')}${metric('Fame',p.fame??'—','Current fame points')}${metric('Vehicles',d.vehicles?.length||0,'Tracked vehicles')}<div class="card span8"><h3 style="margin-top:0">Welcome back, ${esc(p.name||state.me.displayName)}</h3><p style="color:var(--muted);line-height:1.7">Watcher has assembled your Outpost X services into one secure command network. Everything below is tied to your Discord identity and linked SCUM account.</p><div class="grid" style="margin-top:15px">${service('taxi','🚁','Airlift Taxi','Request emergency transport and view your cooldown.',d.airlift?.ready?'READY':'COOLDOWN')}${service('events','📅','Events','Browse upcoming events and manage your RSVPs.',(d.events||[]).filter(e=>e.status==='open').length+' UPCOMING')}${service('playershops','🏪','Player Shops','Browse storefronts or manage your own shop.')}${service('lore','📖','Player Lore','Create and browse roleplay character profiles.')}${service('squads','👥','Squad Finder','Find a squad or manage your recruiting post.')}${service('history','🧾','Watcher History','Review 15 days of Watcher activity.')}${service('vehicles','🚗','Vehicles','View your linked vehicles and insurance.')}</div></div><div class="card span4"><h3>Current Status</h3><div class="list">${statusRow('Account Link',p.steamId?'Linked':'Not linked')}${statusRow('Airlift',d.airlift?.ready?'Ready':d.airlift?.nextRide?`Ready ${fmt(d.airlift.nextRide)}`:'Unknown')}${statusRow('Dirtbike',d.rental?.status||'None')}${statusRow('Player Shop',d.myShop?.shop_name||'Not created')}${statusRow('Lore Profile',d.myLore?.character_name||'Not created')}</div></div></div>`}
else if(state.section==='staff')renderStaff(v);else if(state.section==='vehicles') renderVehicles(v,d);else if(state.section==='insurance')renderInsurance(v,d);else if(state.section==='taxi')renderTaxi(v,d);else if(state.section==='rental')renderRental(v,d);else if(state.section==='shop')renderServerShop(v,d);else if(state.section==='events')renderEvents(v,d);else if(state.section==='playershops')renderPlayerShops(v,d);else if(state.section==='squads')renderSquads(v,d);else if(state.section==='lore')renderLore(v,d);else if(state.section==='history')renderHistory(v,d.transactions||[],false);else if(state.section==='admin')renderAdmin(v,d);else if(state.section==='surveillance'){if(!(state.me.isOwner||state.me.permissions?.use_surveillance))return go('dashboard');title('ADMIN SURVEILLANCE','48-Hour Movement DVR');v.innerHTML='<iframe class="surveillance" src="/tracker/view"></iframe>'}}
function statusRow(a,b){return `<div class="row"><div><b>${esc(a)}</b></div><span>${esc(b)}</span></div>`}
function renderStaff(v){
  title('OUTPOST X PERSONNEL','Outpost X Staff');
  const staff=[
    {name:'Josh',role:'Owner',image:'josh',tag:'Server Owner · Development · Watcher Systems',quote:'The person responsible for all of this.',owner:true},
    {name:'Nivy',role:'Admin',image:'nivy',tag:'Unicorn Queen · Community Support · Events',quote:'Bringing magic, mayhem, and just enough order to keep Outpost X alive.',magic:true},
    {name:'Cat',role:'Admin',image:'cat',tag:'Community · Player Support · Chaos Management',quote:'Helpful, suspicious, and apparently a delight.'},
    {name:'Deathbloom',role:'Admin',image:'deathbloom',tag:'Player Support · Community · Problem Solving',quote:'Calm support for questionable situations.'},
    {name:'CrazyLady',role:'Admin',image:'crazylady',tag:'New Player Support · Community · Group Mom',quote:'Keeping everyone alive, fed, and slightly insulted.'},
    {name:'OneEyedDude',role:'Admin',image:'oneeyeddude',tag:'Player Support · Technical Help · Long-Range Judgment',quote:'Watching quietly and judging from a safe distance.'},
  ];
  v.innerHTML=`<section class="staffIntro card"><div><span class="staffKicker">THE TEAM BEHIND THE WALLS</span><h3>Meet the people behind Outpost X.</h3><p>The people keeping Outpost X running, helping players, and occasionally containing or causing the chaos.</p></div><article class="watcherStaffCard"><div class="watcherScan"></div><img src="/portal/assets/staff/watcher-staff.webp" alt="The Watcher"><div class="watcherStaffCopy"><span class="status good">SYSTEM ONLINE</span><small>CUSTOM BOT · SERVER INTELLIGENCE</small><h3>The Watcher</h3><p>Automation, player services, monitoring, events, surveillance, and questionable decision support.</p></div></article></section><section class="staffGrid">${staff.map(s=>`<article class="staffCard ${s.owner?'ownerCard':''} ${s.magic?'magicCard':''}"><div class="staffPortrait"><img src="/portal/assets/staff/${s.image}.webp" alt="${esc(s.name)}"><div class="staffGlow"></div><span class="staffRole ${s.owner?'ownerRole':''}">${esc(s.role)}</span></div><div class="staffBody"><small>${esc(s.tag)}</small><h3>${esc(s.name)}</h3><p>${esc(s.quote)}</p></div></article>`).join('')}</section><section class="staffHelp card"><div><span class="staffKicker">NEED STAFF HELP?</span><h3>Use the ticket system so the right person can help.</h3><p>For account problems, vehicle issues, rule questions, shop approval, reports, or technical support, open a ticket through Discord instead of privately messaging staff.</p></div><a class="btn primary" href="https://discord.com/channels/1516269432538661025/1531709557997306027" target="_blank" rel="noopener">Open Discord</a></section>`;
}
const FALLBACK_PORTAL_MAP={width:2048,height:2048,uX:-0.00134396890,uY:0.0000000676414083,u0:831.454665,vX:-0.00000000142817301,vY:-0.00134384750,v0:831.522683};
function portalMap(){return state.data?.mapCalibration||FALLBACK_PORTAL_MAP}
const SECTOR_ROWS=['D','C','B','A','Z'],SECTOR_COLS=['4','3','2','1','0'];

const mapZoomStates=new Map();
const PORTAL_TILE_CONFIG={baseDimension:2048,highDimension:14481,highTileSize:2048,highColumns:8,highRows:8,switchZoom:2.15,maxZoom:9};
function tileMapMarkup(id,leftPct,topPct,startZoom=3.2,kind='vehicle'){
  return `<div class="tileMapViewport zoomableMap" id="${id}" data-focus-x="${leftPct}" data-focus-y="${topPct}" data-start-zoom="${startZoom}"><div class="tileMapBase"></div><div class="tileMapTiles"></div><span class="precisionMarker ${kind==='event'?'eventMarker':'vehicleMarker'}" aria-label="Exact recorded location"><span></span></span>${mapZoomControls(id)}<div class="mapZoomHint">Scroll or use +/− to zoom • drag to move</div></div>`;
}
function initZoomableMap(id){
  const viewport=$(id);if(!viewport)return;
  const tiles=viewport.querySelector('.tileMapTiles'),base=viewport.querySelector('.tileMapBase'),marker=viewport.querySelector('.precisionMarker');if(!tiles||!base||!marker)return;
  const focusX=Math.max(0,Math.min(1,Number(viewport.dataset.focusX||50)/100)),focusY=Math.max(0,Math.min(1,Number(viewport.dataset.focusY||50)/100));
  const startZoom=Math.max(1,Math.min(PORTAL_TILE_CONFIG.maxZoom,Number(viewport.dataset.startZoom||1)));
  const st={zoom:startZoom,panX:0,panY:0,focusX,focusY,drag:null,lastLevel:'',tileKeys:new Set()};mapZoomStates.set(id,st);
  const clamp=()=>{const r=viewport.getBoundingClientRect(),mx=r.width*(st.zoom-1)/2,my=r.height*(st.zoom-1)/2;st.panX=Math.max(-mx,Math.min(mx,st.panX));st.panY=Math.max(-my,Math.min(my,st.panY))};
  const screen=(nx,ny,r)=>({x:(nx-.5)*r.width*st.zoom+r.width/2+st.panX,y:(ny-.5)*r.height*st.zoom+r.height/2+st.panY});
  const renderTiles=()=>{
    const r=viewport.getBoundingClientRect();if(!r.width||!r.height)return;
    base.style.transform=`translate(${st.panX}px,${st.panY}px) scale(${st.zoom})`;
    const mp=screen(st.focusX,st.focusY,r);marker.style.left=`${mp.x}px`;marker.style.top=`${mp.y}px`;
    const useHi=st.zoom>=PORTAL_TILE_CONFIG.switchZoom;
    tiles.style.display=useHi?'block':'none';base.style.display=useHi?'none':'block';
    if(useHi){
      const dim=PORTAL_TILE_CONFIG.highDimension,tile=PORTAL_TILE_CONFIG.highTileSize;
      const leftN=Math.max(0,.5-(r.width/2+st.panX)/(r.width*st.zoom)),rightN=Math.min(1,.5+(r.width/2-st.panX)/(r.width*st.zoom));
      const topN=Math.max(0,.5-(r.height/2+st.panY)/(r.height*st.zoom)),bottomN=Math.min(1,.5+(r.height/2-st.panY)/(r.height*st.zoom));
      const x0=Math.max(0,Math.floor(leftN*dim/tile)),x1=Math.min(PORTAL_TILE_CONFIG.highColumns-1,Math.floor(rightN*dim/tile));
      const y0=Math.max(0,Math.floor(topN*dim/tile)),y1=Math.min(PORTAL_TILE_CONFIG.highRows-1,Math.floor(bottomN*dim/tile));
      const needed=new Set();
      for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){
        const key=`${x}_${y}`;needed.add(key);let img=tiles.querySelector(`[data-tile="${key}"]`);
        if(!img){img=document.createElement('img');img.dataset.tile=key;img.alt='';img.draggable=false;img.src=`/tracker/tiles/hi/${key}.jpg`;tiles.appendChild(img)}
        const nx=(x*tile)/dim,ny=(y*tile)/dim,nw=Math.min(tile,dim-x*tile)/dim,nh=Math.min(tile,dim-y*tile)/dim;
        const a=screen(nx,ny,r),b=screen(nx+nw,ny+nh,r);img.style.left=`${a.x}px`;img.style.top=`${a.y}px`;img.style.width=`${b.x-a.x+1}px`;img.style.height=`${b.y-a.y+1}px`;img.style.display='block';
      }
      tiles.querySelectorAll('img').forEach(img=>{if(!needed.has(img.dataset.tile))img.style.display='none'});
    }
    const z=viewport.querySelector('[data-map-zoom-label]');if(z)z.textContent=`${Math.round(st.zoom*100)}%`;
  };
  st.render=renderTiles;st.clamp=clamp;
  const centerFocus=()=>{const r=viewport.getBoundingClientRect();st.panX=(.5-st.focusX)*r.width*st.zoom;st.panY=(.5-st.focusY)*r.height*st.zoom;clamp();renderTiles()};
  viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect(),old=st.zoom,next=Math.max(1,Math.min(PORTAL_TILE_CONFIG.maxZoom,old*(e.deltaY<0?1.22:1/1.22)));if(next===old)return;const px=e.clientX-r.left-r.width/2,py=e.clientY-r.top-r.height/2,ratio=next/old;st.panX=px-(px-st.panX)*ratio;st.panY=py-(py-st.panY)*ratio;st.zoom=next;clamp();renderTiles()},{passive:false});
  viewport.addEventListener('pointerdown',e=>{if(e.target.closest('.mapZoomControls'))return;viewport.setPointerCapture(e.pointerId);st.drag={x:e.clientX,y:e.clientY,ox:st.panX,oy:st.panY};viewport.classList.add('dragging')});
  viewport.addEventListener('pointermove',e=>{if(!st.drag)return;st.panX=st.drag.ox+(e.clientX-st.drag.x);st.panY=st.drag.oy+(e.clientY-st.drag.y);clamp();renderTiles()});
  const end=()=>{st.drag=null;viewport.classList.remove('dragging')};viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);
  new ResizeObserver(()=>renderTiles()).observe(viewport);centerFocus();
}
function zoomPortalMap(id,dir){const st=mapZoomStates.get(id);if(!st)return;st.zoom=Math.max(1,Math.min(PORTAL_TILE_CONFIG.maxZoom,st.zoom*(dir>0?1.28:1/1.28)));if(st.zoom===1){st.panX=0;st.panY=0}st.clamp();st.render()}
function resetPortalMap(id){const viewport=$(id),st=mapZoomStates.get(id);if(!viewport||!st)return;st.zoom=Math.max(1,Math.min(PORTAL_TILE_CONFIG.maxZoom,Number(viewport.dataset.startZoom||1)));const r=viewport.getBoundingClientRect();st.panX=(.5-st.focusX)*r.width*st.zoom;st.panY=(.5-st.focusY)*r.height*st.zoom;st.clamp();st.render()}
function mapZoomControls(id){return `<div class="mapZoomControls"><button class="mapZoomBtn" type="button" onclick="event.stopPropagation();zoomPortalMap('${id}',-1)" aria-label="Zoom out">−</button><span data-map-zoom-label>100%</span><button class="mapZoomBtn" type="button" onclick="event.stopPropagation();zoomPortalMap('${id}',1)" aria-label="Zoom in">+</button><button class="mapZoomBtn reset" type="button" onclick="event.stopPropagation();resetPortalMap('${id}')">Reset</button></div>`}

function vehicleCoords(x){const candidates=[x?.location,x?.lastLocation,x?.position,x];for(const l of candidates){if(!l||typeof l==='string')continue;const vx=Number(l.x??l.X),vy=Number(l.y??l.Y),vz=Number(l.z??l.Z??0);if(Number.isFinite(vx)&&Number.isFinite(vy))return{x:vx,y:vy,z:Number.isFinite(vz)?vz:0}}return null}
function mapPoint(x,y){const m=portalMap();return{x:m.uX*x+m.uY*y+m.u0,y:m.vX*x+m.vY*y+m.v0}}
function sectorForPoint(q){const m=portalMap(),col=Math.max(0,Math.min(4,Math.floor((q.x/m.width)*5))),row=Math.max(0,Math.min(4,Math.floor((q.y/m.height)*5)));return`${SECTOR_ROWS[row]}${SECTOR_COLS[col]}`}
function vehicleLocation(x){const c=vehicleCoords(x);if(typeof x?.sector==='string'&&x.sector)return x.sector;if(c){const q=mapPoint(c.x,c.y);return `Sector ${sectorForPoint(q)} • X ${Math.round(c.x)} • Y ${Math.round(c.y)} • Z ${Math.round(c.z)}`}const l=x?.location;if(typeof l==='string'&&l)return l;return 'Location unavailable'}
function renderVehicles(v,d){title('PLAYER ASSETS','Vehicles');const rows=(d.vehicles||[]).map((x,i)=>{const c=vehicleCoords(x);return `<button type="button" class="row vehicleRow${c?' clickable':''}" ${c?`onclick="openVehicleMap(${i})"`:''}><div><b>${esc(x.name||x.vehicleName||x.class||'Vehicle')}</b><small>ID ${esc(x.id||x.vehicleId||'Unknown')} • ${esc(vehicleLocation(x))}${x.squadName?` • ${esc(x.squadName)}`:''}</small>${c?'<em>Click to view this vehicle on the map</em>':''}</div><div class="vehicleRowEnd"><span class="status">${esc(x.insured?'INSURED':'UNINSURED')}</span>${c?'<span class="mapArrow">OPEN MAP →</span>':''}</div></button>`}).join('');v.innerHTML=`<div class="card"><div class="list">${rows||'<div class="empty">No vehicles were returned for your linked player or squad.</div>'}</div></div>`}
function openVehicleMap(index){const x=state.data?.vehicles?.[Number(index)],c=vehicleCoords(x);if(!x||!c)return toast('This vehicle does not have a usable recorded location.');const q=mapPoint(c.x,c.y),m=portalMap(),left=Math.max(0,Math.min(100,(q.x/m.width)*100)),top=Math.max(0,Math.min(100,(q.y/m.height)*100)),sector=sectorForPoint(q),name=x.name||x.vehicleName||x.class||'Vehicle',mapId='vehicleMapViewport';openDetailModal(`<div class="detailHero"><div><span class="eyebrow">WATCHER VEHICLE LOCATION</span><h2>${esc(name)}</h2><p>Vehicle ID ${esc(x.id||x.vehicleId||'Unknown')}${x.squadName?` • ${esc(x.squadName)}`:''}</p></div><span class="status ${x.insured?'good':''}">${x.insured?'INSURED':'UNINSURED'}</span></div><section class="vehicleLocationPanel"><div class="eventMapHeader"><div><span class="eyebrow">LAST REPORTED POSITION</span><h3>Sector ${esc(sector)}</h3></div><span class="coordBadge">X ${Math.round(c.x)} • Y ${Math.round(c.y)} • Z ${Math.round(c.z)}</span></div>${tileMapMarkup(mapId,left.toFixed(5),top.toFixed(5),4.2,'vehicle')}<div class="vehicleMapFoot"><span>Map position is based on Watcher’s latest GGCON vehicle location.</span><button class="btn" onclick="navigator.clipboard.writeText('#Teleport ${c.x.toFixed(3)} ${c.y.toFixed(3)} ${c.z.toFixed(3)}').then(()=>toast('Teleport coordinates copied.'))">Copy Coordinates</button></div></section>`);setTimeout(()=>initZoomableMap(mapId),0)}
function renderInsurance(v,d){title('ASSET PROTECTION','Vehicle Insurance');v.innerHTML='<div class="card"><div class="empty">Loading insurance controls…</div></div>';api('/portal/api/insurance/options').then(o=>{const policies=(o.policies||[]).map(x=>`<div class="row"><div><b>${esc(x.vehicle_name||x.vehicle_type||'Vehicle policy')}</b><small>Vehicle ${esc(x.vehicle_id||'—')} • Purchased ${fmt(x.purchased_at)}</small></div><span class="status good">${esc((x.status||'active').toUpperCase())}</span></div>`).join('');const eligible=(o.vehicles||[]).filter(x=>x.eligible).map(x=>`<div class="row"><div><b>${esc(x.label||x.name)}</b><small>Vehicle ID ${esc(x.id)} • ${money(x.price)}</small></div><button class="btn primary" onclick="buyInsurance('${esc(x.id)}')">Insure</button></div>`).join('');const claims=(o.claims||[]).map(x=>`<div class="row"><div><b>${esc(x.policy?.vehicle_name||x.vehicle_name||'Replacement Vehicle')}</b><small>Destroyed vehicle ${esc(x.vehicle_id||'—')}</small></div><button class="btn primary" onclick="redeemInsurance('${esc(x.id)}')">Redeem</button></div>`).join('');v.innerHTML=`<div class="grid"><div class="card span6"><h3>Active Policies</h3><div class="list">${policies||'<div class="empty">No active policies.</div>'}</div></div><div class="card span6"><h3>Available Claims</h3><div class="list">${claims||'<div class="empty">No replacement claims are available.</div>'}</div></div><div class="card span12"><h3>Eligible Vehicles</h3><div class="list">${eligible||'<div class="empty">No eligible uninsured vehicles were found.</div>'}</div></div></div>`}).catch(e=>v.innerHTML=`<div class="card empty">${esc(e.message)}</div>`)}
async function buyInsurance(vehicleId){if(!confirm('Purchase insurance for this vehicle?'))return;try{const r=await api('/portal/api/insurance/buy',{method:'POST',body:JSON.stringify({vehicleId})});toast('Insurance activated.');await refresh();render()}catch(e){toast(e.message)}}
async function redeemInsurance(claimId){if(!confirm('Redeem this insurance claim and spawn the replacement vehicle?'))return;try{await api('/portal/api/insurance/redeem',{method:'POST',body:JSON.stringify({claimId})});toast('Replacement vehicle spawned.');await refresh();render()}catch(e){toast(e.message)}}
function renderTaxi(v,d){
  title('EMERGENCY TRANSPORT','Airlift Taxi');
  const sectors=SECTOR_ROWS.flatMap(row=>SECTOR_COLS.map(col=>`${row}${col}`));
  const selected=state.taxiSector&&state.taxiSector!=='C0'?state.taxiSector:null;
  v.innerHTML=`<div class="grid taxiLayout"><div class="card span8 taxiMapCard"><div class="taxiIntro"><div><h3>Choose Your Destination</h3><p>Airlift cost: <b>${money(1000)}</b>. Select a sector directly on the map, then confirm your ride.</p></div><span class="status ${d.airlift?.ready?'good':'bad'}">${d.airlift?.ready?'READY':'COOLDOWN'}</span></div><div class="taxiMapShell"><img src="/tracker/map.png" alt="SCUM sector map for choosing an Airlift Taxi destination" draggable="false"><div class="taxiSectorGrid">${sectors.map(sector=>`<button type="button" class="taxiSectorCell${selected===sector?' selected':''}${sector==='C0'?' unavailable':''}" data-sector="${sector}" aria-label="${sector==='C0'?'Sector C0 unavailable':'Select sector '+sector}" ${sector==='C0'?'disabled':''} onclick="selectTaxiSector('${sector}')"><span>${sector==='C0'?'UNAVAILABLE':sector}</span></button>`).join('')}</div><div class="taxiMapInstruction">Click a sector on the map</div></div></div><div class="card span4 taxiStatusCard"><h3>Ride Status</h3>${statusRow('Availability',d.airlift?.ready?'READY':'COOLDOWN')}${statusRow('Next Ride',d.airlift?.ready?'Now':fmt(d.airlift?.nextRide))}<div id="taxiSelectionPanel" class="taxiSelectionPanel">${taxiSelectionMarkup(selected,d)}</div><p class="taxiSafety">Do not jump during the airlift sequence. Watcher will position you above the selected sector.</p></div></div>`
}
function taxiSelectionMarkup(sector,d){
  if(!sector)return `<div class="taxiEmptySelection"><b>No destination selected</b><span>Choose a sector from the map.</span></div>`;
  const ready=!!d?.airlift?.ready;
  if(state.taxiPrepared?.sector===sector)return `<div class="taxiSelectedSector prepared"><small>PARACHUTE DELIVERED</small><strong>Sector ${sector}</strong><span>Put on the parachute now. Do not jump or move until Watcher launches you.</span></div><button class="btn primary taxiConfirm" onclick="sendTaxi('${sector}')">🚁 I’m Ready — Send Airlift</button><button class="btn taxiClear" onclick="cancelTaxi()">Cancel Without Charge</button>`;
  return `<div class="taxiSelectedSector"><small>SELECTED DESTINATION</small><strong>Sector ${sector}</strong><span>Step 1 of 2: Watcher will deliver a parachute. You will not be charged or teleported yet.</span></div><button class="btn primary taxiConfirm" ${ready?'':'disabled'} onclick="prepareTaxi('${sector}')">🪂 Prepare Airlift to ${sector}</button><button class="btn taxiClear" onclick="clearTaxiSector()">Clear Selection</button>`
}
function selectTaxiSector(sector){
  if(!sector||sector==='C0')return;
  state.taxiSector=sector;state.taxiPrepared=null;
  document.querySelectorAll('.taxiSectorCell').forEach(cell=>cell.classList.toggle('selected',cell.dataset.sector===sector));
  const panel=$('taxiSelectionPanel');if(panel)panel.innerHTML=taxiSelectionMarkup(sector,state.data);
}
function clearTaxiSector(){state.taxiSector=null;state.taxiPrepared=null;document.querySelectorAll('.taxiSectorCell').forEach(cell=>cell.classList.remove('selected'));const panel=$('taxiSelectionPanel');if(panel)panel.innerHTML=taxiSelectionMarkup(null,state.data)}
async function prepareTaxi(sector){
  if(!confirm(`Prepare an airlift to sector ${sector}? Watcher will spawn a parachute, but you will not be charged or teleported yet.`))return;
  try{
    const r=await api('/portal/api/action/taxi/prepare',{method:'POST',body:JSON.stringify({sector})});
    state.taxiPrepared={sector:r.sector,expiresAt:r.expiresAt};
    const panel=$('taxiSelectionPanel');if(panel)panel.innerHTML=taxiSelectionMarkup(sector,state.data);
    toast('Parachute delivered. Put it on, then press Send Airlift.');
  }catch(e){toast(e.message)}
}
async function sendTaxi(sector){
  if(!confirm(`Are you wearing the parachute and ready to launch to sector ${sector}? After confirming, Watcher will wait 10 seconds so you can return to SCUM. You will be charged $1,000 immediately before teleport.`))return;
  const panel=$('taxiSelectionPanel');
  let remaining=10;
  if(panel)panel.innerHTML=`<div class="taxiSelectedSector prepared launching"><small>AIRLIFT LAUNCH SEQUENCE</small><strong>Sector ${sector}</strong><span>Return to the SCUM game window now. Launching in <b id="taxiCountdown">${remaining}</b> seconds…</span></div><button class="btn primary taxiConfirm" disabled>🚁 Launch Sequence Active</button>`;
  const timer=setInterval(()=>{remaining=Math.max(0,remaining-1);const el=$('taxiCountdown');if(el)el.textContent=remaining;},1000);
  try{
    await api('/portal/api/action/taxi/send',{method:'POST',body:JSON.stringify({sector})});
    clearInterval(timer);
    state.taxiPrepared=null;state.taxiSector=null;
    toast(`Airlift launched to ${sector}. Deploy your parachute and land safely.`);
    await refresh();render();
  }catch(e){
    clearInterval(timer);
    toast(e.message);
    const panelNow=$('taxiSelectionPanel');if(panelNow)panelNow.innerHTML=taxiSelectionMarkup(sector,state.data);
  }
}
async function cancelTaxi(){
  try{await api('/portal/api/action/taxi/cancel',{method:'POST',body:'{}'});}catch{}
  state.taxiPrepared=null;clearTaxiSector();toast('Airlift cancelled. You were not charged.');
}
function renderRental(v,d){title('TEMPORARY TRANSPORT','Dirtbike Rental');const r=d.rental||{};v.innerHTML=`<div class="grid"><div class="card span8"><h3>30-Minute Dirtbike Rental</h3><p style="color:var(--muted)">Cost: <b>${money(500)}</b>. Watcher spawns a tracked dirtbike for 30 minutes and removes it automatically when time expires.</p><button class="btn primary" onclick="requestRental()" ${r.status==='active'?'disabled':''}>${r.status==='active'?'Rental Active':'Rent Dirtbike'}</button></div><div class="card span4"><h3>Rental Status</h3>${statusRow('Status',r.status||'None')}${statusRow('Vehicle ID',r.vehicle_id||'—')}${statusRow('Expires',fmt(r.expires_at))}</div></div>`}
async function requestRental(){if(!confirm('Rent a dirtbike for $500?'))return;try{await api('/portal/api/action/rental',{method:'POST',body:'{}'});toast('Dirtbike rental started.');await refresh()}catch(e){toast(e.message)}}
function renderServerShop(v,d){
  title('WATCHER SUPPLY NETWORK','Server Shop');
  const canManage=state.me?.isOwner||state.me?.permissions?.manage_server_shop;
  const canEdit=state.me?.isOwner||state.me?.permissions?.edit_shop_products;
  const manager=canManage?`<div class="card span12 manageHero"><div><small>${state.me?.isOwner?'OWNER EYES ONLY':'AUTHORIZED SHOP CONTROL'}</small><h2>Server Shop Manager</h2><p>Edit products, prices, quantities, package contents, display order, and availability from the visual inventory manager.</p></div><button class="btn primary" onclick="openServerShopManagerFromStore()">Manage Server Shop</button></div>`:'';
  v.innerHTML=`<div class="grid">${manager}${(d.shopCatalog||[]).map(x=>`<div class="card span4 shopproduct"><div style="font-size:34px">${esc(x.emoji||'📦')}</div><h3>${esc(x.name)}</h3><p style="color:var(--muted);min-height:42px">${esc(x.description||'Emergency supply package')}</p><div class="list" style="margin:12px 0">${(x.contents||[]).map(i=>`<div class="row"><span>${esc(i.label)}</span><b>×${Number(i.qty||1)}</b></div>`).join('')}</div><b style="font-size:24px">${money(x.price)}</b><div class="adminActions" style="margin-top:14px"><button class="btn primary" onclick="buyItem('${esc(x.id)}','${esc(x.name)}',${Number(x.price||0)})">Purchase & Deliver</button>${canEdit?`<button class="btn" onclick="editServerShopProductFromStore('${esc(x.id)}')">Edit Product</button>`:''}</div></div>`).join('')||'<div class="card span12 empty">No server-shop packages are configured.</div>'}</div>`
}
function openServerShopManagerFromStore(){
  if(!(state.me?.isOwner||state.me?.permissions?.manage_server_shop))return toast('You do not have permission to manage the Server Shop.');
  go('admin');
  setTimeout(()=>adminTab('serverShop'),0);
}
async function editServerShopProductFromStore(id){
  if(!(state.me?.isOwner||state.me?.permissions?.edit_shop_products))return toast('You do not have permission to edit Server Shop products.');
  try{
    const r=await api('/portal/api/admin/shop/products');
    shopManagerProducts=r.products||[];
    const product=shopManagerProducts.find(x=>String(x.id)===String(id)||String(x.slug)===String(id));
    if(!product)throw new Error('That product could not be found in the managed catalogue.');
    openShopProductEditor(product.id);
  }catch(e){toast(e.message)}
}
async function buyItem(id,name,price){if(!confirm(`Purchase ${name} for ${money(price)} and deliver it beside your linked SCUM character?`))return;try{const r=await api('/portal/api/action/shop',{method:'POST',body:JSON.stringify({id})});toast(`${r.package?.name||name} delivered near ${r.playerName||'your character'}.`);await refresh()}catch(e){toast(e.message)}}
function renderCollection(v,eye,t,items,card){title(eye,t);v.innerHTML=`<div class="searchbar"><input id="filter" placeholder="Search ${t.toLowerCase()}" oninput="filterCards()"></div><div class="grid" id="cards">${items.map(card).join('')||'<div class="card span12 empty">Nothing has been published yet.</div>'}</div>`}
function filterCards(){const q=$('filter').value.toLowerCase();document.querySelectorAll('#cards>[data-search]').forEach(e=>e.style.display=e.dataset.search.includes(q)?'block':'none')}
function imageStrip(urls){const a=Array.isArray(urls)?urls.filter(Boolean):[];return a.length?`<div class="imageStrip">${a.map(u=>`<img src="${esc(u)}" loading="lazy">`).join('')}</div>`:''}
function shopCard(x){return `<button type="button" class="card span4 directoryCard" data-search="${esc(`${x.shop_name} ${x.owner_name||''} ${x.shop_type} ${x.location_text||''}`.toLowerCase())}" onclick="openShopDetail('${esc(x.id)}')">${imageStrip(x.image_urls)}<div class="directoryTop"><span class="status ${x.is_open?'good':''}">${x.is_open?'OPEN':'CLOSED'}</span><span class="openHint">OPEN PROFILE ›</span></div><h3>${esc(x.shop_name||'Player Shop')}</h3><p>${esc(shortText(x.description||'No description',150))}</p><small>${esc(x.location_text||'Location hidden')} • ${esc(x.shop_type||'General')}</small></button>`}
function squadCard(x){return `<button type="button" class="card span4 directoryCard" data-search="${esc(`${x.squad_name} ${x.play_style} ${x.active_times}`.toLowerCase())}" onclick="openSquadDetail('${esc(x.id)}')"><div class="directoryTop"><span class="status ${x.is_recruiting?'good':''}">${x.is_recruiting?'RECRUITING':'CLOSED'}</span><span class="openHint">OPEN LISTING ›</span></div><h3>${esc(x.squad_name||'Squad')}</h3><p>${esc(shortText(x.description||'No description',150))}</p><div class="list compact">${statusRow('Members',x.member_count||'Not listed')}${statusRow('Style',x.play_style||'Any')}${statusRow('Active',x.active_times||'Any time')}</div></button>`}
function loreCard(x){return `<button type="button" class="card span4 directoryCard" data-search="${esc(`${x.character_name} ${x.category} ${x.faction_squad||''} ${x.origin}`.toLowerCase())}" onclick="openLoreDetail('${esc(x.id)}')">${imageStrip(x.image_urls)}<div class="directoryTop"><span class="status good">${esc(x.rp_status||'RP')}</span><span class="openHint">READ FULL LORE ›</span></div><h3>${esc(x.character_name||'Unknown Survivor')}</h3><p>${esc(shortText(x.backstory||x.personality||'No lore summary',150))}</p><small>${esc(x.category||'Survivor')} • ${esc(x.faction_squad||'Unaffiliated')}</small></button>`}
function shortText(value,max=160){const t=String(value||'').replace(/\s+/g,' ').trim();return t.length>max?t.slice(0,max-1)+'…':t}
function fullText(value,fallback='Not provided'){const t=String(value||'').trim();return t?esc(t).replace(/\n/g,'<br>'):`<span class="mutedText">${esc(fallback)}</span>`}
function detailImages(urls,caption=''){const a=Array.isArray(urls)?urls.filter(Boolean):[];if(!a.length)return'';return `<div class="detailGallery">${a.map((u,i)=>`<button type="button" onclick="openImageViewer('${esc(u)}')"><img src="${esc(u)}" alt="Image ${i+1}"></button>`).join('')}</div>${caption?`<div class="imageCaption">${fullText(caption,'')}</div>`:''}`}
function detailField(label,value,fallback='Not provided'){return `<div class="detailField"><small>${esc(label)}</small><div>${fullText(value,fallback)}</div></div>`}
function openDetailModal(html){const modal=$('modal').querySelector('.modal');modal.classList.add('detailModal');$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function openShopDetail(id){const x=(state.data?.shops||[]).find(v=>String(v.id)===String(id))||(String(state.data?.myShop?.id)===String(id)?state.data.myShop:null);if(!x)return toast('That shop is no longer available.');openDetailModal(`<div class="detailHero"><div><span class="eyebrow">PLAYER MARKETPLACE</span><h2>${esc(x.shop_name||'Player Shop')}</h2><p>${esc(x.owner_name?`Operated by ${x.owner_name}`:'Player-owned storefront')}</p></div><span class="status ${x.is_open?'good':''}">${x.is_open?'OPEN':'CLOSED'}</span></div>${detailImages(x.image_urls,x.storefront_text)}<div class="detailGrid">${detailField('Shop Type',x.shop_type,'General')}${detailField('Location / Sector',x.location_text,'Location not listed')}${detailField('Owner',x.owner_name||x.owner_display_name,'Not listed')}${detailField('Last Updated',x.updated_at?fmt(x.updated_at):'Not available')}</div><section class="detailSection"><h3>About This Shop</h3><div class="longText">${fullText(x.description,'No shop description has been added.')}</div></section>`)}
function openSquadDetail(id){const x=(state.data?.squads||[]).find(v=>String(v.id)===String(id))||(String(state.data?.mySquad?.id)===String(id)?state.data.mySquad:null);if(!x)return toast('That squad listing is no longer available.');openDetailModal(`<div class="detailHero"><div><span class="eyebrow">SQUAD NETWORK</span><h2>${esc(x.squad_name||'Squad')}</h2><p>${esc(x.owner_name?`Listed by ${x.owner_name}`:'Outpost X squad listing')}</p></div><span class="status ${x.is_recruiting?'good':''}">${x.is_recruiting?'RECRUITING':'NOT RECRUITING'}</span></div><div class="detailGrid">${detailField('Members',x.member_count,'Not listed')}${detailField('Play Style',x.play_style,'Any')}${detailField('Active Times',x.active_times,'Any time')}${detailField('Voice Chat',x.voice_chat,'Optional')}${detailField('Leader / Contact',x.owner_name||x.owner_display_name,'Listing owner')}${detailField('Last Updated',x.updated_at?fmt(x.updated_at):'Not available')}</div><section class="detailSection"><h3>Squad Description</h3><div class="longText">${fullText(x.description,'No squad description has been added.')}</div></section>`)}
function openLoreDetail(id){const all=[...(state.data?.lore||[])];if(state.data?.myLore&&!all.some(v=>String(v.id)===String(state.data.myLore.id)))all.push(state.data.myLore);const x=all.find(v=>String(v.id)===String(id));if(!x)return toast('That lore profile is no longer available.');openDetailModal(`<div class="detailHero"><div><span class="eyebrow">ROLEPLAY ARCHIVE</span><h2>${esc(x.character_name||'Unknown Survivor')}</h2><p>${esc(x.title_nickname||x.category||'Outpost X Character')}</p></div><span class="status good">${esc(x.rp_status||'RP')}</span></div>${detailImages(x.image_urls,x.image_caption)}<div class="detailGrid">${detailField('Category',x.category,'Survivor')}${detailField('Origin',x.origin)}${detailField('Faction / Squad',x.faction_squad,'Unaffiliated')}${detailField('RP Status',x.rp_status,'Casual RP')}${detailField('Title / Nickname',x.title_nickname)}${detailField('Last Updated',x.updated_at?fmt(x.updated_at):'Not available')}</div><section class="detailSection"><h3>Backstory</h3><div class="longText">${fullText(x.backstory,'No backstory has been added.')}</div></section><section class="detailSection"><h3>Personality</h3><div class="longText">${fullText(x.personality,'No personality details have been added.')}</div></section><section class="detailSection"><h3>Goals & Motives</h3><div class="longText">${fullText(x.goals,'No goals or motives have been added.')}</div></section><section class="detailSection"><h3>Additional Lore</h3><div class="longText">${fullText(x.extra_lore,'No additional lore has been added.')}</div></section>`)}
function openImageViewer(url){openDetailModal(`<div class="imageViewer"><img src="${esc(url)}" alt="Full-size image"></div>`)}
function manageBar(titleText,desc,buttons){return `<div class="card span12 manageHero"><div><small>YOUR LISTING</small><h2>${esc(titleText)}</h2><p>${esc(desc)}</p></div><div class="adminActions">${buttons}</div></div>`}
function renderPlayerShops(v,d){title('PLAYER MARKETPLACE','Player Shops');const mine=d.myShop;const controls=mine?manageBar(mine.shop_name,mine.is_open?'Your storefront is open.':'Your storefront is closed.',`<button class="btn primary" onclick="openShopForm()">Edit Shop</button><button class="btn" onclick="openShopImages()">Manage Images</button><button class="btn" onclick="shopAction('toggle')">${mine.is_open?'Close':'Open'} Shop</button><button class="btn dangerBtn" onclick="shopAction('delete')">Delete Shop</button>`):manageBar('Create Your Storefront','A Shop Owner role is required. Trading still happens in SCUM.',`<button class="btn primary" onclick="openShopForm()">Create Shop</button>`);v.innerHTML=`<div class="grid">${controls}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search shops" oninput="filterCards()"></div><div class="grid" id="cards">${(d.shops||[]).map(shopCard).join('')||'<div class="empty">No shops yet.</div>'}</div></div></div>`}
function openShopForm(){const x=state.data.myShop||{};$('modalBody').innerHTML=`<h2>${x.id?'Edit':'Create'} Player Shop</h2><div class="formgrid"><label>Shop Name<input id="fShopName" maxlength="80" value="${esc(x.shop_name||'')}"></label><label>Location / Sector<input id="fShopLocation" maxlength="100" value="${esc(x.location_text||'')}"></label><label>Shop Type<input id="fShopType" maxlength="80" value="${esc(x.shop_type||'General')}"></label><label class="full">Description<textarea id="fShopDesc" rows="5">${esc(x.description||'')}</textarea></label><label class="full">Text Below Images<textarea id="fShopText" rows="4">${esc(x.storefront_text||'')}</textarea></label></div><button class="btn primary" onclick="saveShop()">Save Storefront</button>`;$('modal').classList.remove('hidden');restoreDraft('playerShop');armDraft('playerShop')}
async function saveShop(){const body={shop_name:$('fShopName').value,location_text:$('fShopLocation').value,shop_type:$('fShopType').value,description:$('fShopDesc').value,storefront_text:$('fShopText').value};try{await api(`/portal/api/player-shop/${state.data.myShop?'update':'create'}`,{method:'POST',body:JSON.stringify(body)});closeModal();clearDraft('playerShop');toast('Shop saved.');await refresh()}catch(e){toast(e.message)}}
function openShopImages(){const x=state.data.myShop||{};$('modalBody').innerHTML=`<h2>Shop Images</h2><p>Choose up to 5 images. Saving replaces the current image set; leave empty to remove all images.</p><label>Images<input id="shopFiles" type="file" accept="image/*" multiple></label><label>Text Below Images<textarea id="shopCaption" rows="4">${esc(x.storefront_text||'')}</textarea></label><button class="btn primary" onclick="saveShopImages()">Replace Images</button>`;$('modal').classList.remove('hidden');restoreDraft('playerShopImages');armDraft('playerShopImages')}
async function filesToData(input){const files=[...input.files].slice(0,5);return Promise.all(files.map(f=>new Promise((resolve,reject)=>{if(f.size>8*1024*1024)return reject(new Error(`${f.name} is larger than 8 MB.`));const r=new FileReader();r.onload=()=>resolve({name:f.name,data:r.result});r.onerror=()=>reject(new Error(`Could not read ${f.name}.`));r.readAsDataURL(f)})))}
async function saveShopImages(){try{const images=await filesToData($('shopFiles'));await api('/portal/api/player-shop/images',{method:'POST',body:JSON.stringify({images,storefront_text:$('shopCaption').value})});closeModal();clearDraft('playerShopImages');toast('Shop images updated.');await refresh()}catch(e){toast(e.message)}}
async function shopAction(action){if(action==='delete'&&!confirm('Permanently delete your shop?'))return;try{await api(`/portal/api/player-shop/${action}`,{method:'POST',body:'{}'});toast(action==='delete'?'Shop deleted.':'Shop status updated.');await refresh()}catch(e){toast(e.message)}}
function renderSquads(v,d){title('SQUAD NETWORK','Squad Finder');const mine=d.mySquad;const controls=mine?manageBar(mine.squad_name,mine.is_recruiting?'Your squad is recruiting.':'Your listing is closed.',`<button class="btn primary" onclick="openSquadForm()">Edit Listing</button><button class="btn" onclick="squadAction('toggle')">${mine.is_recruiting?'Stop':'Start'} Recruiting</button><button class="btn dangerBtn" onclick="squadAction('delete')">Delete Listing</button>`):manageBar('Post Your Squad','Create one listing and manage it yourself.',`<button class="btn primary" onclick="openSquadForm()">Create Listing</button>`);v.innerHTML=`<div class="grid">${controls}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search squads" oninput="filterCards()"></div><div class="grid" id="cards">${(d.squads||[]).map(squadCard).join('')||'<div class="empty">No squads listed.</div>'}</div></div></div>`}
function openSquadForm(){const x=state.data.mySquad||{};$('modalBody').innerHTML=`<h2>${x.id?'Edit':'Create'} Squad Listing</h2><div class="formgrid"><label>Squad Name<input id="sqName" value="${esc(x.squad_name||'')}"></label><label>Member Count<input id="sqMembers" value="${esc(x.member_count||'')}"></label><label>Play Style<input id="sqStyle" value="${esc(x.play_style||'')}"></label><label>Active Times<input id="sqTimes" value="${esc(x.active_times||'')}"></label><label>Voice Chat<select id="sqVoice"><option>Optional</option><option>Required</option><option>Not Used</option></select></label><label class="full">Description<textarea id="sqDesc" rows="5">${esc(x.description||'')}</textarea></label></div><button class="btn primary" onclick="saveSquad()">Save Listing</button>`;$('sqVoice').value=x.voice_chat||'Optional';$('modal').classList.remove('hidden');restoreDraft('squadListing');armDraft('squadListing')}
async function saveSquad(){const b={squad_name:$('sqName').value,member_count:$('sqMembers').value,play_style:$('sqStyle').value,active_times:$('sqTimes').value,voice_chat:$('sqVoice').value,description:$('sqDesc').value};try{await api(`/portal/api/squad/${state.data.mySquad?'update':'create'}`,{method:'POST',body:JSON.stringify(b)});closeModal();clearDraft('squadListing');toast('Squad listing saved.');await refresh()}catch(e){toast(e.message)}}
async function squadAction(action){if(action==='delete'&&!confirm('Delete your Squad Finder listing?'))return;try{await api(`/portal/api/squad/${action}`,{method:'POST',body:'{}'});toast('Squad listing updated.');await refresh()}catch(e){toast(e.message)}}
const LORE_CATS=['Survivor','Trader','Mercenary','Medic','Mechanic','Hunter','Military','Drifter','Outlaw / Bandit','Faction Member','Civilian','Other'];
function renderLore(v,d){title('ROLEPLAY ARCHIVE','Player Lore');const mine=d.myLore;const controls=mine?manageBar(mine.character_name,mine.is_published?'Your lore is published.':'Your lore is hidden.',`<button class="btn primary" onclick="openLoreForm()">Edit Lore</button><button class="btn" onclick="openLoreImages()">Manage Images</button><button class="btn" onclick="loreAction('toggle')">${mine.is_published?'Hide':'Publish'} Lore</button><button class="btn dangerBtn" onclick="loreAction('delete')">Delete Lore</button>`):manageBar('Create Your Character','Build a full RP profile with categories, status and images.',`<button class="btn primary" onclick="openLoreForm()">Create Lore</button>`);v.innerHTML=`<div class="grid">${controls}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search names, categories, factions or origin" oninput="filterCards()"></div><div class="grid" id="cards">${(d.lore||[]).map(loreCard).join('')||'<div class="empty">No published lore yet.</div>'}</div></div></div>`}
function openLoreForm(){const x=state.data.myLore||{};$('modalBody').innerHTML=`<h2>${x.id?'Edit':'Create'} Player Lore</h2><div class="formgrid"><label>Character Name<input id="loName" value="${esc(x.character_name||'')}"></label><label>Title / Nickname<input id="loTitle" value="${esc(x.title_nickname||'')}"></label><label>Faction / Squad<input id="loFaction" value="${esc(x.faction_squad||'')}"></label><label>Origin<input id="loOrigin" value="${esc(x.origin||'')}"></label><label>Category<select id="loCat">${LORE_CATS.map(c=>`<option>${c}</option>`).join('')}</select></label><label>RP Status<select id="loStatus"><option>Open to RP</option><option>Casual RP</option><option>Not Seeking RP</option></select></label><label class="full">Backstory<textarea id="loBack" rows="8">${esc(x.backstory||'')}</textarea></label><label class="full">Personality<textarea id="loPerson" rows="4">${esc(x.personality||'')}</textarea></label><label class="full">Goals / Motives<textarea id="loGoals" rows="4">${esc(x.goals||'')}</textarea></label><label class="full">Additional Lore<textarea id="loExtra" rows="4">${esc(x.extra_lore||'')}</textarea></label></div><button class="btn primary" onclick="saveLore()">Save Lore</button>`;$('loCat').value=x.category||'Survivor';$('loStatus').value=x.rp_status||'Casual RP';$('modal').classList.remove('hidden');restoreDraft('playerLore');armDraft('playerLore')}
async function saveLore(){const b={character_name:$('loName').value,title_nickname:$('loTitle').value,faction_squad:$('loFaction').value,origin:$('loOrigin').value,category:$('loCat').value,rp_status:$('loStatus').value,backstory:$('loBack').value,personality:$('loPerson').value,goals:$('loGoals').value,extra_lore:$('loExtra').value};try{await api(`/portal/api/lore/${state.data.myLore?'update':'create'}`,{method:'POST',body:JSON.stringify(b)});closeModal();clearDraft('playerLore');toast('Lore saved.');await refresh()}catch(e){toast(e.message)}}
function openLoreImages(){const x=state.data.myLore||{};$('modalBody').innerHTML=`<h2>Lore Images</h2><p>Choose up to 5 images. Saving replaces the current image set; leave empty to remove all images.</p><label>Images<input id="loreFiles" type="file" accept="image/*" multiple></label><label>Image Caption<textarea id="loreCaption" rows="4">${esc(x.image_caption||'')}</textarea></label><button class="btn primary" onclick="saveLoreImages()">Replace Images</button>`;$('modal').classList.remove('hidden');restoreDraft('playerLoreImages');armDraft('playerLoreImages')}
async function saveLoreImages(){try{const images=await filesToData($('loreFiles'));await api('/portal/api/lore/images',{method:'POST',body:JSON.stringify({images,image_caption:$('loreCaption').value})});closeModal();clearDraft('playerLoreImages');toast('Lore images updated.');await refresh()}catch(e){toast(e.message)}}
async function loreAction(action){if(action==='delete'&&!confirm('Permanently delete your lore profile?'))return;try{await api(`/portal/api/lore/${action}`,{method:'POST',body:'{}'});toast('Lore profile updated.');await refresh()}catch(e){toast(e.message)}}

function localEventInput(t){if(!t)return'';const d=new Date(t),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function eventById(id){return (state.data?.events||[]).find(x=>String(x.id)===String(id))}
function eventLocationMap(e){const m=e?.map;if(!m)return'';const pm=portalMap(),left=Math.max(0,Math.min(100,(Number(m.map_x)/pm.width)*100)),top=Math.max(0,Math.min(100,(Number(m.map_y)/pm.height)*100)),mapId=`eventMapViewport-${String(e.id||'event').replace(/[^a-zA-Z0-9_-]/g,'')}`;return `<section class="eventLocation"><div class="eventMapHeader"><div><span class="eyebrow">RECORDED EVENT LOCATION</span><h3>Sector ${esc(m.sector||'Unknown')}</h3></div><span class="coordBadge">X ${Number(e.coordinate_x).toFixed(0)} • Y ${Number(e.coordinate_y).toFixed(0)} • Z ${Number(e.coordinate_z).toFixed(0)}</span></div>${tileMapMarkup(mapId,left.toFixed(5),top.toFixed(5),4.2,'event')}<div class="rawCoords">${esc(e.coordinate_raw||`{X=${e.coordinate_x} Y=${e.coordinate_y} Z=${e.coordinate_z}}`)}</div></section>`}
function eventCard(e){const open=e.status==='open',thumb=Array.isArray(e.image_urls)&&e.image_urls[0]?`<div class="eventThumb" style="background-image:url('${esc(e.image_urls[0])}')"></div>`:'';return `<div class="card span6 eventCard" data-search="${esc(`${e.title} ${e.location||''} ${e.description||''} ${e.map?.sector||''}`.toLowerCase())}" onclick="openEvent('${esc(e.id)}')">${thumb}<div class="eventTop"><div><span class="eyebrow">${esc((e.recurrence_label||e.recurrence||'One-time').toUpperCase())}</span><h3>${esc(e.title)}</h3></div><span class="status ${open?'good':''}">${open?'OPEN':'CLOSED'}</span></div><p class="eventWhen">🕒 ${esc(e.formatted_time||fmt(e.event_time))}</p><p>📍 ${esc(e.location||'Location TBA')}${e.map?.sector?` • <b>Sector ${esc(e.map.sector)}</b>`:''}</p><p class="eventPreview">${esc(e.description||'')}</p><div class="eventFoot"><span>👥 ${Number(e.rsvp_count||0)} RSVP${Number(e.rsvp_count||0)===1?'':'s'}</span><b>${e.my_rsvp?'✅ YOU ARE GOING':'OPEN DETAILS →'}</b></div></div>`}
function renderEvents(v,d){title('OUTPOST OPERATIONS','Events');const events=d.events||[];const admin=(state.me.isOwner||state.me.permissions?.manage_events)?`<div class="card span12 manage"><div><small>ADMIN EVENT CONTROL</small><h3>Create and manage server events</h3><p>Add event images, paste exact SCUM coordinates, and Watcher will show the correct sector with a location marker.</p></div><button class="btn primary" onclick="openEventForm()">+ Create Event</button></div>`:'';v.innerHTML=`<div class="grid">${admin}<div class="card span12"><div class="searchbar"><input id="filter" placeholder="Search events, sectors, locations or descriptions" oninput="filterCards()"></div><div class="grid" id="cards">${events.map(eventCard).join('')||'<div class="empty">No upcoming events are currently posted.</div>'}</div></div></div>`}
function openEvent(id){const e=eventById(id);if(!e)return toast('Event not found.');const admin=(state.me.isOwner||state.me.permissions?.manage_events)?`<div class="detailActions"><button class="btn" onclick="openEventForm('${esc(e.id)}')">Edit Event</button><button class="btn" onclick="eventStatus('${esc(e.id)}','${e.status==='open'?'closed':'open'}')">${e.status==='open'?'Close Event':'Reopen Event'}</button><button class="btn dangerBtn" onclick="deleteEvent('${esc(e.id)}')">Delete Event</button></div>`:'';$('modalBody').innerHTML=`<div class="detailHero"><span class="eyebrow">${esc(e.recurrence_label||e.recurrence||'One-time')}</span><h2>${esc(e.title)}</h2><div class="detailMeta"><span>🕒 ${esc(e.formatted_time||fmt(e.event_time))}</span><span>📍 ${esc(e.location)}</span>${e.map?.sector?`<span>🗺️ Sector ${esc(e.map.sector)}</span>`:''}<span>👥 ${Number(e.rsvp_count||0)} attending</span></div></div>${detailImages(e.image_urls,'')}${eventLocationMap(e)}<div class="detailText">${esc(e.description).replace(/\n/g,'<br>')}</div><div class="detailActions">${e.status==='open'?`<button class="btn ${e.my_rsvp?'':'primary'}" onclick="eventRsvp('${esc(e.id)}',${e.my_rsvp?'false':'true'})">${e.my_rsvp?'Cancel RSVP':'RSVP to Event'}</button>`:'<span class="status">EVENT CLOSED</span>'}</div>${admin}`;$('modal').querySelector('.modal').classList.add('detailModal');$('modal').classList.remove('hidden');setTimeout(()=>{const map=$('modalBody').querySelector('.zoomableMap');if(map)initZoomableMap(map.id)},0)}
function openEventForm(id=''){const e=id?eventById(id):null;$('modalBody').innerHTML=`<h2>${e?'Edit':'Create'} Event</h2><div class="formgrid"><label class="full">Event title<input id="evTitle" maxlength="100" value="${esc(e?.title||'')}"></label><label>Location name<input id="evLocation" maxlength="200" value="${esc(e?.location||'')}"></label><label>Date and time<input id="evTime" type="datetime-local" value="${localEventInput(e?.event_time)}"></label><label>Recurrence<select id="evRecurrence"><option value="none">One-time</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="monthly">Monthly</option></select></label><label class="full">SCUM coordinates <small>(optional)</small><textarea id="evCoordinates" rows="3" placeholder="{X=221249.375 Y=-291857.969 Z=17184.834|P=348.760956 Y=160.196045 R=0.000000}">${esc(e?.coordinate_raw||'')}</textarea><small>Paste the complete coordinates exactly as copied from SCUM. Watcher will calculate the sector and place the map dot.</small></label><label class="full">Event images <small>(up to 5)</small><input id="evFiles" type="file" accept="image/*" multiple><small>${e&&Array.isArray(e.image_urls)&&e.image_urls.length?`${e.image_urls.length} image(s) currently attached. Choose files only when replacing them.`:'Images will appear in Discord and on the Command Center event page.'}</small></label>${e&&Array.isArray(e.image_urls)&&e.image_urls.length?`<label class="checkline full"><input id="evRemoveImages" type="checkbox"> Remove all current event images</label>`:''}<label class="full">Description<textarea id="evDescription" rows="8" maxlength="2000">${esc(e?.description||'')}</textarea></label></div><button class="btn primary" onclick="saveEvent('${esc(e?.id||'')}')">${e?'Save Changes':'Post Event'}</button>`;$('modal').querySelector('.modal').classList.remove('detailModal');$('modal').classList.remove('hidden');$('evRecurrence').value=e?.recurrence||'none';const draftName=`event:${id||'new'}`;restoreDraft(draftName);armDraft(draftName)}
async function saveEvent(id){const title=$('evTitle').value.trim(),location=$('evLocation').value.trim(),description=$('evDescription').value.trim(),coordinates=$('evCoordinates').value.trim(),raw=$('evTime').value,recurrence=$('evRecurrence').value,files=$('evFiles');if(!title||!location||!description||!raw)return toast('Complete every required event field.');const eventTime=new Date(raw).toISOString();try{const images=files?.files?.length?await filesToData(files):[];const removeImages=!!$('evRemoveImages')?.checked;const replaceImages=!!images.length||removeImages;await api(id?'/portal/api/events/update':'/portal/api/events/create',{method:'POST',body:JSON.stringify({id,title,location,description,coordinates,eventTime,recurrence,images,replaceImages})});closeModal();clearDraft(`event:${id||'new'}`);toast(id?'Event updated.':'Event posted to Discord.');await refresh();go('events')}catch(e){toast(e.message)}}

async function eventRsvp(id,attending){try{await api('/portal/api/events/rsvp',{method:'POST',body:JSON.stringify({id,attending})});closeModal();toast(attending?'RSVP saved. Reminders are enabled.':'RSVP removed.');await refresh();go('events')}catch(e){toast(e.message)}}
async function eventStatus(id,status){if(!confirm(`${status==='open'?'Reopen':'Close'} this event?`))return;try{await api('/portal/api/events/status',{method:'POST',body:JSON.stringify({id,status})});closeModal();toast(`Event ${status==='open'?'reopened':'closed'}.`);await refresh();go('events')}catch(e){toast(e.message)}}
async function deleteEvent(id){if(!confirm('Permanently delete this event, its Discord post and all RSVPs?'))return;try{await api('/portal/api/events/delete',{method:'POST',body:JSON.stringify({id})});closeModal();toast('Event deleted.');await refresh();go('events')}catch(e){toast(e.message)}}

function renderHistory(v,tx,admin){if(v.id!=='adminLedger')title(admin?'ADMIN LEDGER':'WATCHER LEDGER',admin?'Transaction Control':'My Watcher History');v.innerHTML=`<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>Date</th>${admin?'<th>Player</th>':''}<th>Action</th><th>Amount</th><th>Status</th>${admin?'<th>Admin</th>':''}</tr></thead><tbody>${tx.map(x=>`<tr><td>${fmt(x.created_at)}</td>${admin?`<td>${esc(x.player_name||x.steam_id||'Unknown')}</td>`:''}<td>${esc(x.title||x.type)}</td><td class="amount ${Number(x.amount)>=0?'pos':'neg'}">${Number(x.amount)?money(x.amount):'—'}</td><td>${esc(x.refund_status||x.status)}</td>${admin?`<td>${(state.me.isOwner||state.me.permissions?.issue_refunds)&&x.refundable&&Math.abs(Number(x.amount||0))>Number(x.refunded_amount||0)?`<button class="btn" onclick='refund(${JSON.stringify(x)})'>Refund</button>`:'—'}</td>`:''}</tr>`).join('')||'<tr><td colspan="6" class="empty">No Watcher history in the last 15 days.</td></tr>'}</tbody></table></div></div>`}
function renderAdmin(v,d){if(!state.me.isAdmin)return go('dashboard');title('ADMIN OPERATIONS','Watcher Control Deck');const p=state.me.permissions||{};const tabs=[];if(state.me.isOwner||p.search_players)tabs.push(`<button class="btn primary" onclick="adminTab('players')">Player Controls</button>`);if(state.me.isOwner||p.view_transactions)tabs.push(`<button class="btn" onclick="adminTab('ledger')">Transaction Ledger & Refunds</button>`);if(state.me.isOwner||p.moderate_player_shops||p.moderate_player_lore||p.moderate_squads)tabs.push(`<button class="btn" onclick="adminTab('content')">Player Content Moderation</button>`);if(state.me.isOwner||p.manage_events)tabs.push(`<button class="btn" onclick="adminTab('eventTriggers')">Admin Event Triggers</button>`);if(state.me.isOwner||p.manage_server_shop)tabs.push(`<button class="btn" onclick="adminTab('serverShop')">Server Shop Manager</button>`);if(state.me.isOwner)tabs.push(`<button class="btn ownerOnlyBtn" onclick="adminTab('owner')">🔒 Owner Controls</button>`);v.innerHTML=`<div class="adminTabs">${tabs.join('')}</div><div id="adminArea"></div>`;adminTab(state.me.isOwner||p.search_players?'players':state.me.isOwner||p.view_transactions?'ledger':state.me.isOwner||p.manage_server_shop?'serverShop':state.me.isOwner||p.manage_events?'eventTriggers':'content')}
function adminTab(tab){state.adminSubtab=tab||'players';const a=$('adminArea');if(tab==='ledger'){renderAdminLedger(a);return}if(tab==='content'){renderContentModeration(a);return}if(tab==='serverShop'){renderServerShopManager(a);return}if(tab==='eventTriggers'){renderAdminEventTriggers(a);return}if(tab==='owner'){renderOwnerControls(a);return}a.innerHTML=`<div class="grid"><div class="card span12"><h3>Find a Player</h3><p style="color:var(--muted)">Search by SCUM name or Steam64 ID. Raw log/data-pull commands stay in Discord and are intentionally not shown here.</p><div class="searchbar"><input id="adminSearch" placeholder="Player name or Steam64 ID" onkeydown="if(event.key==='Enter')adminSearch()"><button class="btn primary" onclick="adminSearch()">Search</button></div><div id="adminResults" class="list"></div></div><div id="adminPlayer" class="span12"></div></div>`}

let specialEventAdminData={event:{active:false},onlinePlayers:[]};
function eventRemainingLabel(event){if(!event?.active)return 'No special event is currently active.';const left=Math.max(0,Number(event.endsAt||0)-Date.now());const min=Math.floor(left/60000),sec=Math.floor((left%60000)/1000);return `${event.type==='hunt'?'Watcher Hunt':event.type==='risk'?'Risk or Reward':'Special Event'} • ${event.phase||'active'} • ${min}m ${sec}s remaining`;}
async function renderAdminEventTriggers(a){
  a.innerHTML=`<div class="grid"><div class="card span12"><div class="sectionHead"><div><small>WATCHER SPECIAL EVENTS</small><h2>Admin Event Triggers</h2><p>Launch and monitor special in-game Watcher events. Players join and interact entirely through SCUM chat.</p></div><button class="btn" onclick="loadAdminEventTriggers()">Refresh Status</button></div><div id="specialEventStatus" class="list"><div class="empty">Loading event status…</div></div></div><div id="specialEventCards" class="span12"></div></div>`;
  await loadAdminEventTriggers();
}
async function loadAdminEventTriggers(){
  const statusBox=$('specialEventStatus'),cards=$('specialEventCards');
  try{
    specialEventAdminData=await api('/portal/api/admin/event-triggers');
    const e=specialEventAdminData.event||{active:false};
    statusBox.innerHTML=e.active?`<div class="row"><div><b>${esc(eventRemainingLabel(e))}</b><small>${e.type==='hunt'?`Participants: ${Number(e.participantCount||0)} • Hidden bounty: ${esc(e.bounty?.name||'Unknown')} • Win radius: 50 m`:e.type==='risk'?`Contestant: ${esc(e.contestant?.name||'Waiting for player')} • Safe ${money(e.safeReward)} • Maximum ${money(e.maxReward)}`:'Active special event'}</small></div><button class="btn dangerBtn" onclick="endSpecialEvent()">End Active Event</button></div>`:`<div class="empty">No special event is active. Choose one below.</div>`;
    const players=(specialEventAdminData.onlinePlayers||[]).filter(x=>x.steamId);
    const playerOptions=['<option value="">Random online player</option>',...players.map(x=>`<option value="${esc(x.steamId)}">${esc(x.name)} — ${esc(x.steamId)}</option>`)].join('');
    cards.innerHTML=`<div class="grid">
      <article class="card span4"><small>CARGO FRENZY</small><h3>Scatter Cargo Across the Island</h3><p>Launch the existing safe-spawn Cargo Frenzy from the Command Center.</p><label>Number of cargo drops<input id="cargoTriggerCount" type="number" min="1" max="30" value="10"></label><button class="btn primary" onclick="startCargoTrigger()" ${e.active?'disabled':''}>Trigger Cargo Frenzy</button></article>
      <article class="card span4"><small>WATCHER HUNT</small><h3>Hidden Bounty Hunt</h3><p>Players type <b>!hunt</b> in SCUM chat to join and <b>!scan</b> for private directional clues.</p><div class="formgrid"><label class="full">Hidden bounty<select id="huntBounty">${playerOptions}</select></label><label>Join window (seconds)<input id="huntJoinSeconds" type="number" min="30" max="300" value="120"></label><label>Duration (minutes)<input id="huntDuration" type="number" min="5" max="60" value="20"></label><label>Scan cooldown (seconds)<input id="huntScanCooldown" type="number" min="10" max="180" value="30"></label><label>Winner reward<input id="huntReward" type="number" min="0" step="100" value="2500"></label><label class="full form-check form-switch"><input class="form-check-input" id="huntAllowStaff" type="checkbox" checked><span class="form-check-label">Allow Owner/Admin as the bounty</span></label></div><button class="btn primary" onclick="startWatcherHunt()" ${e.active?'disabled':''}>Start Watcher Hunt</button><small>First registered hunter confirmed within 50 metres for two samples wins.</small></article>
      <article class="card span4"><small>RISK OR REWARD</small><h3>Make a Watcher Offer</h3><p>First eligible player to type <b>!risk</b> chooses <b>!safe</b> or <b>!riskit</b> privately in-game.</p><div class="formgrid"><label>Safe reward<input id="riskSafeReward" type="number" min="0" step="100" value="500"></label><label>Maximum reward<input id="riskMaxReward" type="number" min="500" step="100" value="3000"></label><label>Acceptance window (seconds)<input id="riskAcceptSeconds" type="number" min="30" max="300" value="90"></label><label class="form-check form-switch"><input class="form-check-input" id="riskAllowStorm" type="checkbox" checked><span class="form-check-label">Allow Watcher storm outcome</span></label></div><button class="btn primary" onclick="startRiskReward()" ${e.active?'disabled':''}>Start Risk or Reward</button></article>
    </div>`;
  }catch(err){statusBox.innerHTML=`<div class="empty">${esc(err.message)}</div>`;if(cards)cards.innerHTML='';}
}
async function triggerSpecialEvent(action,options={}){try{await api('/portal/api/admin/event-triggers',{method:'POST',body:JSON.stringify({action,options})});toast(action==='cargo'?'Cargo Frenzy triggered.':action==='hunt'?'Watcher Hunt started.':action==='risk'?'Risk or Reward started.':'Special event updated.');await loadAdminEventTriggers()}catch(err){toast(err.message)}}
function startCargoTrigger(){triggerSpecialEvent('cargo',{count:Number($('cargoTriggerCount')?.value||10)})}
function startWatcherHunt(){triggerSpecialEvent('hunt',{bountySteamId:$('huntBounty')?.value||'',allowStaffBounty:!!$('huntAllowStaff')?.checked,joinSeconds:Number($('huntJoinSeconds')?.value||120),durationMinutes:Number($('huntDuration')?.value||20),scanCooldownSeconds:Number($('huntScanCooldown')?.value||30),rewardCash:Number($('huntReward')?.value||2500)})}
function startRiskReward(){triggerSpecialEvent('risk',{safeReward:Number($('riskSafeReward')?.value||500),maxReward:Number($('riskMaxReward')?.value||3000),acceptSeconds:Number($('riskAcceptSeconds')?.value||90),allowStorm:!!$('riskAllowStorm')?.checked})}
async function endSpecialEvent(){if(!confirm('End the currently active Watcher special event?'))return;await triggerSpecialEvent('end',{reason:'Ended by staff from the Command Center'})}
function renderContentModeration(a){const d=state.data,p=state.me.permissions||{},owner=state.me.isOwner;const cards=[];if(owner||p.moderate_player_shops)cards.push(`<div class="card span4"><h3>Player Shops</h3><div class="list">${(d.shops||[]).map(x=>moderationRow('shop',x.id,x.shop_name,x.is_open?'OPEN':'CLOSED')).join('')||'<div class="empty">None</div>'}</div></div>`);if(owner||p.moderate_squads)cards.push(`<div class="card span4"><h3>Squad Listings</h3><div class="list">${(d.squads||[]).map(x=>moderationRow('squad',x.id,x.squad_name,x.is_recruiting?'RECRUITING':'CLOSED')).join('')||'<div class="empty">None</div>'}</div></div>`);if(owner||p.moderate_player_lore)cards.push(`<div class="card span4"><h3>Player Lore</h3><div class="list">${[...(d.lore||[]),...(d.myLore&&!d.lore?.some(x=>x.id===d.myLore.id)?[d.myLore]:[])].map(x=>moderationRow('lore',x.id,x.character_name,x.is_published?'PUBLISHED':'HIDDEN')).join('')||'<div class="empty">None</div>'}</div></div>`);a.innerHTML=`<div class="grid">${cards.join('')||'<div class="card span12 empty">No content moderation permissions are enabled for your role.</div>'}</div>`}
function moderationRow(kind,id,name,status){return `<div class="row"><div><b>${esc(name)}</b><small>${esc(status)}</small></div><div><button class="btn" onclick="moderateContent('${kind}','${esc(id)}','toggle')">Toggle</button> <button class="btn dangerBtn" onclick="moderateContent('${kind}','${esc(id)}','delete')">Delete</button></div></div>`}
async function moderateContent(kind,id,action){if(action==='delete'&&!confirm(`Delete this ${kind} permanently?`))return;try{await api('/portal/api/admin/content',{method:'POST',body:JSON.stringify({kind,id,action})});toast('Content updated.');await refresh();go('admin');adminTab('content')}catch(e){toast(e.message)}}
function renderAdminLedger(a){
  const l=state.adminLedger;
  a.innerHTML=`<div class="card ledgerControls"><div class="ledgerToolbar"><div class="ledgerSearch"><input id="ledgerSearch" value="${esc(l.search)}" placeholder="Search player, Steam ID or action" onkeydown="if(event.key==='Enter')applyLedgerFilters()"><button class="btn primary" onclick="applyLedgerFilters()">Search</button></div><label>Type<select id="ledgerCategory" onchange="applyLedgerFilters()"><option value="all">All Watcher Activity</option><option value="server_shop">Server Shop</option><option value="insurance">Insurance</option><option value="taxi">Airlift Taxi</option><option value="rental">Dirtbike Rental</option><option value="refund">Refunds</option><option value="admin">Admin Adjustments</option></select></label><label>Status<select id="ledgerStatus" onchange="applyLedgerFilters()"><option value="all">All Statuses</option><option value="completed">Completed</option><option value="failed">Failed</option><option value="refunded">Partially / Fully Refunded</option></select></label><label>Rows<select id="ledgerPageSize" onchange="applyLedgerFilters()"><option>25</option><option>50</option><option>100</option></select></label><button class="btn" onclick="resetLedgerFilters()">Clear Filters</button></div><div class="ledgerSummary"><span id="ledgerSummary">Loading transactions…</span><small>Watcher activity from the last 15 days only.</small></div></div><div id="adminLedger"><div class="card empty">Loading transaction ledger…</div></div>`;
  $('ledgerCategory').value=l.category;$('ledgerStatus').value=l.status;$('ledgerPageSize').value=String(l.pageSize);loadAdminLedger();
}
async function loadAdminLedger(){
  const l=state.adminLedger,box=$('adminLedger');if(!box)return;box.innerHTML='<div class="card empty">Watcher is loading transactions…</div>';
  const q=new URLSearchParams({page:String(l.page),pageSize:String(l.pageSize),category:l.category,status:l.status});if(l.search)q.set('search',l.search);
  try{const r=await api(`/portal/api/admin/transactions?${q}`);l.rows=r.transactions||[];l.total=Number(r.total||0);l.page=Number(r.page||1);l.pages=Number(r.pages||1);drawAdminLedger(box);}
  catch(e){box.innerHTML=`<div class="card empty">${esc(e.message)}</div>`}
}
function drawAdminLedger(box){
  const l=state.adminLedger;const canRefund=state.me.isOwner||state.me.permissions?.issue_refunds;
  $('ledgerSummary').textContent=`${l.total.toLocaleString()} transaction${l.total===1?'':'s'} • Page ${l.page} of ${l.pages}`;
  box.innerHTML=`<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>Date</th><th>Player</th><th>Action</th><th>Amount</th><th>Status</th><th>Admin</th></tr></thead><tbody>${l.rows.map(x=>`<tr><td>${fmt(x.created_at)}</td><td><b>${esc(x.player_name||'Unknown')}</b><small class="ledgerSteam">${esc(x.steam_id||'')}</small></td><td>${esc(x.title||x.type)}</td><td class="amount ${Number(x.amount)>=0?'pos':'neg'}">${Number(x.amount)?money(x.amount):'—'}</td><td>${esc(x.refund_status||x.status)}</td><td>${canRefund&&x.refundable&&Math.abs(Number(x.amount||0))>Number(x.refunded_amount||0)?`<button class="btn" onclick='refund(${JSON.stringify(x)})'>Refund</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No transactions match these filters.</td></tr>'}</tbody></table></div><div class="ledgerPager"><button class="btn" ${l.page<=1?'disabled':''} onclick="ledgerPage(${l.page-1})">← Previous</button><span>Page ${l.page} of ${l.pages}</span><button class="btn" ${l.page>=l.pages?'disabled':''} onclick="ledgerPage(${l.page+1})">Next →</button></div></div>`;
}
function applyLedgerFilters(){const l=state.adminLedger;l.search=($('ledgerSearch')?.value||'').trim();l.category=$('ledgerCategory')?.value||'all';l.status=$('ledgerStatus')?.value||'all';l.pageSize=Number($('ledgerPageSize')?.value||25);l.page=1;loadAdminLedger()}
function resetLedgerFilters(){state.adminLedger={page:1,pageSize:25,category:'all',status:'all',search:'',total:0,pages:1,rows:[]};renderAdminLedger($('adminArea'))}
function ledgerPage(page){const l=state.adminLedger;l.page=Math.max(1,Math.min(l.pages,Number(page)||1));loadAdminLedger();document.querySelector('.ledgerControls')?.scrollIntoView({behavior:'smooth',block:'start'})}
async function adminSearch(){const q=$('adminSearch').value.trim();if(!q)return toast('Enter a player name or Steam ID.');try{const r=await api('/portal/api/admin/search',{method:'POST',body:JSON.stringify({query:q})});$('adminResults').innerHTML=(r.players||[]).map(p=>`<button class="row adminresult" onclick="openAdminPlayer('${esc(p.steamId)}','${esc(p.name)}')"><div><b>${esc(p.name)}</b><small>${esc(p.steamId)}</small></div><span class="status ${p.online?'good':''}">${p.online?'ONLINE':'OFFLINE'}</span></button>`).join('')||'<div class="empty">No players matched that search.</div>'}catch(e){toast(e.message)}}
function openAdminPlayer(steamId,name){const p=state.me.permissions||{},owner=state.me.isOwner;const buttons=[`<button class="btn primary" onclick="adminView('${steamId}','details')">Player Details</button>`,`<button class="btn" onclick="adminView('${steamId}','vehicles')">Vehicles</button>`,`<button class="btn" onclick="adminView('${steamId}','squad')">Squad</button>`,`<button class="btn" onclick="adminView('${steamId}','nearby')">Nearby Vehicles</button>`];if(owner||p.adjust_balances)buttons.push(`<button class="btn" onclick="adminAdjustOpen('${steamId}','cash',1)">Add Cash</button>`,`<button class="btn dangerBtn" onclick="adminAdjustOpen('${steamId}','cash',-1)">Remove Cash</button>`,`<button class="btn" onclick="adminAdjustOpen('${steamId}','fame',1)">Add Fame</button>`,`<button class="btn dangerBtn" onclick="adminAdjustOpen('${steamId}','fame',-1)">Remove Fame</button>`);if(owner||p.jail_release)buttons.push(`<button class="btn dangerBtn" onclick="adminJail('${steamId}','jail')">Jail</button>`,`<button class="btn" onclick="adminJail('${steamId}','unjail')">Unjail</button>`);if(owner||p.ban_unban)buttons.push(`<button class="btn dangerBtn" onclick="adminModerateOpen('${steamId}','ban')">Ban Player</button>`,`<button class="btn" onclick="adminModerateOpen('${steamId}','unban')">Unban Player</button>`);buttons.push(`<button class="btn dangerBtn" onclick="adminModerateOpen('${steamId}','unlink')">Unlink Discord</button>`);$('adminPlayer').innerHTML=`<div class="card"><div class="playerHead"><div><small>SELECTED PLAYER</small><h2>${esc(name)}</h2><span>${esc(steamId)}</span></div><button class="btn" onclick="adminView('${steamId}','details')">Refresh Details</button></div><div class="adminActions">${buttons.join('')}</div><pre class="adminOutput" id="adminOutput">Select an action above.</pre></div>`;adminView(steamId,'details')}
async function adminView(steamId,view){const o=$('adminOutput');o.textContent='Watcher is loading…';try{const r=await api('/portal/api/admin/player',{method:'POST',body:JSON.stringify({steamId,view})});o.textContent=r.content||'No data returned.'}catch(e){o.textContent=e.message}}
function adminAdjustOpen(steamId,kind,sign){$('modalBody').innerHTML=`<h2>${sign>0?'Add':'Remove'} ${kind==='cash'?'Cash':'Fame'}</h2><div class="formgrid"><label>Amount<input id="adminAmount" type="number" min="1"></label><label class="full">Required reason<textarea id="adminReason" rows="4"></textarea></label></div><button class="btn primary" onclick="adminAdjust('${steamId}','${kind}',${sign})">Confirm Adjustment</button>`;$('modal').classList.remove('hidden')}
async function adminAdjust(steamId,kind,sign){const n=Math.floor(Number($('adminAmount').value)),reason=$('adminReason').value.trim();if(!n||n<1||!reason)return toast('Enter an amount and reason.');try{await api('/portal/api/admin/adjust',{method:'POST',body:JSON.stringify({steamId,kind,amount:n*sign,reason})});closeModal();toast('Player balance updated.');adminView(steamId,'details')}catch(e){toast(e.message)}}
async function adminJail(steamId,action){if(!confirm(`${action==='jail'?'Jail':'Release'} this player?`))return;try{const r=await api('/portal/api/admin/jail',{method:'POST',body:JSON.stringify({steamId,action})});toast(r.message||'Action completed.');adminView(steamId,'details')}catch(e){toast(e.message)}}
function adminModerateOpen(steamId,action){const word=action.toUpperCase(),needsReason=action!=='unlink';$('modalBody').innerHTML=`<h2>${word} Player</h2>${needsReason?'<label>Required reason<textarea id="modReason" rows="4"></textarea></label>':''}<label>Type ${word} to confirm<input id="modConfirm"></label><button class="btn ${action==='ban'||action==='unlink'?'dangerBtn':'primary'}" onclick="adminModerate('${steamId}','${action}')">Confirm ${word}</button>`;$('modal').classList.remove('hidden')}
async function adminModerate(steamId,action){const reason=$('modReason')?.value.trim()||'',confirmWord=$('modConfirm').value.trim();try{const r=await api('/portal/api/admin/moderate',{method:'POST',body:JSON.stringify({steamId,action,reason,confirm:confirmWord})});closeModal();toast(r.message||'Action completed.')}catch(e){toast(e.message)}}
function refund(x){$('modalBody').innerHTML=`<h2>Refund Transaction</h2><p>${esc(x.player_name||x.steam_id)} • ${esc(x.title)}</p><div class="formgrid"><label>Refund amount<input id="refundAmount" type="number" min="1" max="${Math.abs(Number(x.amount))-Number(x.refunded_amount||0)}" value="${Math.abs(Number(x.amount))-Number(x.refunded_amount||0)}"></label><label class="full">Required reason<textarea id="refundReason" rows="4"></textarea></label></div><button class="btn primary" style="margin-top:12px" onclick="confirmRefund('${x.id}')">Issue Refund</button>`;$('modal').classList.remove('hidden')}
async function confirmRefund(id){const amount=Number($('refundAmount').value),reason=$('refundReason').value.trim();if(!reason)return toast('A refund reason is required.');try{await api('/portal/api/admin/refund',{method:'POST',body:JSON.stringify({transactionId:id,amount,reason})});closeModal();toast('Refund completed.');await loadAdminLedger();silentRefresh(true)}catch(e){toast(e.message)}}

let shopManagerProducts=[];let shopDraftItems=[];let shopCatalogSearchResults=[];
async function renderServerShopManager(a){a.innerHTML=`<div class="grid"><div class="card span12 manageHero"><div><small>OWNER CONTROLLED SUPPLY NETWORK</small><h2>Server Shop Manager</h2><p>Create packages, search the live GGCON item catalogue, choose quantities, change prices, and enable or disable products without editing code.</p></div><button class="btn primary" onclick="openShopProductEditor()">+ New Product</button></div><div class="card span12"><div class="searchbar"><input id="shopManagerFilter" placeholder="Search products or categories" oninput="filterShopManagerCards()"><button class="btn" onclick="loadShopManager()">Refresh</button></div><div class="shopManagerGrid" id="shopManagerGrid"><div class="empty">Loading products…</div></div></div></div>`;await loadShopManager()}
async function loadShopManager(){try{const r=await api('/portal/api/admin/shop/products');shopManagerProducts=r.products||[];drawShopManager()}catch(e){$('shopManagerGrid').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function drawShopManager(){const box=$('shopManagerGrid');if(!box)return;box.innerHTML=shopManagerProducts.map(p=>`<article class="card shopManagerCard" data-search="${esc(`${p.name} ${p.category} ${p.description}`.toLowerCase())}"><div class="shopManagerTop"><span class="shopEmoji">${esc(p.emoji||'📦')}</span><span class="status ${p.enabled?'good':''}">${p.enabled?'ENABLED':'DISABLED'}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description||'No description')}</p><small>${esc(p.category||'General')} • ${money(p.price)} • ${(p.items||[]).length} item types</small><div class="list compact">${(p.items||[]).slice(0,5).map(i=>`<div class="row"><span>${esc(i.label)}</span><b>×${Number(i.qty||1)}</b></div>`).join('')}${(p.items||[]).length>5?`<div class="empty">+${p.items.length-5} more</div>`:''}</div><div class="adminActions"><button class="btn primary" onclick="openShopProductEditor('${esc(p.id)}')">Edit</button><button class="btn" onclick="duplicateShopProduct('${esc(p.id)}')">Duplicate</button><button class="btn dangerBtn" onclick="deleteShopProduct('${esc(p.id)}','${esc(p.name)}')">Delete</button></div></article>`).join('')||'<div class="empty">No products configured.</div>'}
function filterShopManagerCards(){const q=$('shopManagerFilter').value.toLowerCase();document.querySelectorAll('#shopManagerGrid [data-search]').forEach(x=>x.style.display=x.dataset.search.includes(q)?'':'none')}
function duplicateShopProduct(id){const p=shopManagerProducts.find(x=>String(x.id)===String(id));if(!p)return;openShopProductEditor('',{...p,id:null,name:`${p.name} Copy`,slug:''})}
function openShopProductEditor(id='',override=null){const p=override||shopManagerProducts.find(x=>String(x.id)===String(id))||{name:'',emoji:'📦',description:'',category:'General',price:0,enabled:true,sortOrder:shopManagerProducts.length,items:[]};shopDraftItems=(p.items||[]).map(x=>({...x}));$('modalBody').innerHTML=`<h2>${p.id?'Edit':'Create'} Server Shop Product</h2><div class="formgrid"><label>Product name<input id="spName" value="${esc(p.name||'')}"></label><label>Emoji<input id="spEmoji" value="${esc(p.emoji||'📦')}" maxlength="16"></label><label>Category<input id="spCategory" value="${esc(p.category||'General')}"></label><label>Price<input id="spPrice" type="number" min="0" value="${Number(p.price||0)}"></label><label>Display order<input id="spSort" type="number" value="${Number(p.sortOrder||0)}"></label><label>Enabled<select id="spEnabled"><option value="true" ${p.enabled!==false?'selected':''}>Yes</option><option value="false" ${p.enabled===false?'selected':''}>No</option></select></label><label class="full">Description<textarea id="spDescription" rows="3">${esc(p.description||'')}</textarea></label></div><div class="catalogBuilder"><div class="builderHead"><div><small>LIVE GGCON ITEM CATALOGUE</small><h3>Package Contents</h3></div></div><div class="searchbar"><input id="catalogSearch" placeholder="Search item name or internal spawn ID" onkeydown="if(event.key==='Enter')searchShopItems()"><button class="btn" onclick="searchShopItems()">Search Inventory</button></div><div id="catalogResults" class="catalogResults"></div><h4>Selected Items</h4><div id="shopDraftItems" class="list"></div></div><div class="modalFooter"><button class="btn primary" onclick="saveShopProduct('${esc(p.id||'')}')">Save Product</button><button class="btn" onclick="closeModal()">Cancel</button></div>`;$('modal').querySelector('.modal').classList.add('detailModal');$('modal').classList.remove('hidden');const draftName=`serverShopProduct:${p.id||'new'}`;restoreDraft(draftName,{extraRestore:d=>{if(Array.isArray(d.shopDraftItems))shopDraftItems=d.shopDraftItems.map(x=>({...x}))}});drawShopDraftItems();armDraft(draftName,()=>({shopDraftItems}));$('catalogResults').innerHTML='<div class="empty">Type at least 2 characters to search the SCUM catalogue.</div>'}
async function searchShopItems(){const q=($('catalogSearch')?.value||'').trim();const box=$('catalogResults');if(!box)return;if(q.length<2){box.innerHTML='<div class="empty">Type at least 2 characters to search the SCUM catalogue.</div>';return}box.innerHTML='<div class="empty">Searching cached inventory…</div>';try{const r=await api(`/portal/api/admin/shop/items?q=${encodeURIComponent(q)}`);shopCatalogSearchResults=r.items||[];box.innerHTML=shopCatalogSearchResults.map((i,n)=>`<button class="catalogItem" onclick="addShopDraftItem(shopCatalogSearchResults[${n}])"><span>📦</span><div><b>${esc(i.label)}</b><small>${esc(i.itemClass)} • ${esc(i.category||'SCUM Item')}</small></div><strong>ADD</strong></button>`).join('')||'<div class="empty">No matching SCUM items.</div>'}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function addShopDraftItem(item){const existing=shopDraftItems.find(x=>x.itemClass===item.itemClass);if(existing)existing.qty=Math.min(1000,Number(existing.qty||1)+1);else shopDraftItems.push({label:item.label,itemClass:item.itemClass,qty:1});drawShopDraftItems()}
function drawShopDraftItems(){const box=$('shopDraftItems');if(!box)return;box.innerHTML=shopDraftItems.map((i,n)=>`<div class="row"><div><b>${esc(i.label)}</b><small>${esc(i.itemClass)}</small></div><div class="qtyControl"><button class="btn" onclick="changeShopQty(${n},-1)">−</button><input type="number" min="1" max="1000" value="${Number(i.qty||1)}" onchange="setShopQty(${n},this.value)"><button class="btn" onclick="changeShopQty(${n},1)">+</button><button class="btn dangerBtn" onclick="removeShopDraftItem(${n})">Remove</button></div></div>`).join('')||'<div class="empty">Search the inventory and add at least one item.</div>'}
function changeShopQty(n,d){shopDraftItems[n].qty=Math.max(1,Math.min(1000,Number(shopDraftItems[n].qty||1)+d));drawShopDraftItems()}function setShopQty(n,v){shopDraftItems[n].qty=Math.max(1,Math.min(1000,Math.floor(Number(v||1))))}function removeShopDraftItem(n){shopDraftItems.splice(n,1);drawShopDraftItems()}
async function saveShopProduct(id){const body={id:id||null,name:$('spName').value.trim(),emoji:$('spEmoji').value.trim()||'📦',category:$('spCategory').value.trim()||'General',price:Number($('spPrice').value),sortOrder:Number($('spSort').value),enabled:$('spEnabled').value==='true',description:$('spDescription').value.trim(),items:shopDraftItems};if(!body.name||!body.items.length)return toast('Add a product name and at least one item.');try{await api('/portal/api/admin/shop/product',{method:'POST',body:JSON.stringify(body)});closeModal();clearDraft(`serverShopProduct:${id||'new'}`);toast('Server shop product saved.');await refresh();adminTab('serverShop')}catch(e){toast(e.message)}}
async function deleteShopProduct(id,name){if(!confirm(`Delete ${name} permanently?`))return;try{await api('/portal/api/admin/shop/delete',{method:'POST',body:JSON.stringify({id})});toast('Product deleted.');await refresh();adminTab('serverShop')}catch(e){toast(e.message)}}
async function renderOwnerControls(a){if(!state.me.isOwner){a.innerHTML='<div class="card empty">Owner access required.</div>';return}a.innerHTML=`<div class="grid"><div class="card span12 ownerControlHero"><small>OWNER EYES ONLY</small><h2>Command Center Permissions</h2><p>Choose which tools the Admin role can use. Owner access always remains enabled and cannot be delegated or disabled.</p></div><div class="card span12"><div id="permissionGrid" class="permissionGrid"><div class="empty">Loading permissions…</div></div><div class="adminActions"><button class="btn primary" onclick="saveOwnerPermissions()">Save Permission Changes</button><button class="btn" onclick="restorePermissionDefaults()">Restore Recommended Defaults</button></div></div></div>`;try{const r=await api('/portal/api/owner/permissions');state.ownerPermissions=r.permissions||{};state.permissionCatalog=r.catalog||[];drawPermissionGrid()}catch(e){$('permissionGrid').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function drawPermissionGrid(){const box=$('permissionGrid');box.innerHTML=`<div class="permissionHeader"><b>Tool</b><b>Owner</b><b>Admin</b></div>${state.permissionCatalog.map(x=>`<label class="permissionRow ${x.dangerous?'dangerPermission':''}"><span><b>${esc(x.label)}</b>${x.dangerous?'<small>Powerful permission — enable carefully</small>':''}</span><input type="checkbox" checked disabled aria-label="Owner always allowed"><input class="adminPerm" data-key="${esc(x.key)}" type="checkbox" ${state.ownerPermissions[x.key]?'checked':''}></label>`).join('')}`}
function restorePermissionDefaults(){for(const x of state.permissionCatalog)state.ownerPermissions[x.key]=x.defaultAdmin===true;drawPermissionGrid();toast('Recommended defaults loaded. Save to apply them.')}
async function saveOwnerPermissions(){const permissions={};document.querySelectorAll('.adminPerm').forEach(x=>permissions[x.dataset.key]=x.checked);const dangerousEnabled=state.permissionCatalog.filter(x=>x.dangerous&&permissions[x.key]&&!state.ownerPermissions[x.key]);if(dangerousEnabled.length&&!confirm(`Enable ${dangerousEnabled.length} powerful Admin permission(s)?`))return;try{await api('/portal/api/owner/permissions',{method:'POST',body:JSON.stringify({permissions})});state.ownerPermissions=permissions;state.me.permissions=permissions;toast('Admin permissions updated.');nav()}catch(e){toast(e.message)}}

function closeModal(){if(saveDraft.active?.save)saveDraft.active.save();saveDraft.active=null;const modal=$('modal').querySelector('.modal');modal.classList.remove('detailModal');$('modal').classList.add('hidden')}
async function refresh(){const ui=preserveUi();state.data=await api('/portal/api/overview');state.me=state.data.me;state.overviewHash=stableHash(state.data);render();restoreUi(ui)}
$('refreshBtn').onclick=refresh;$('backBtn').onclick=goBack;$('homeBtn').onclick=goHome;updatePageNav();$('dismissSessionWarning')?.addEventListener('click',dismissSessionWarning);
load().catch(e=>{if(state.sessionExpired)return;document.body.innerHTML=`<div style="padding:40px;color:#ff8d8d"><h2>Command Center unavailable</h2><p>${esc(e.message)}</p><p>Please reopen the Command Center from Discord.</p></div>`});
